const DATA_ROOT = "data/processed/";
const BOUNDS_95 = [[48.89,1.60],[49.25,2.60]];
const qualityLabels = {"2":"Bon état","3":"État moyen","4":"État médiocre","5":"Mauvais état","U":"Non classé"};
const qualityColors = {"2":"#20a06b","3":"#f0c541","4":"#ee8b38","5":"#d94a4a","U":"#88959e"};

const sources = [
  {id:"cours",title:"Cours d’eau du Val-d’Oise — arrêté préfectoral",date:"18 février 2021",dataset:"cours-deau-du-val-doise-arrete-prefectoral-ndeg2017-13817-1",file:"cours_eau.geojson",group:"Milieux",color:"#0063cb",kind:"line",count:"1 425 tronçons",active:true},
  {id:"qualite",title:"Qualité de l’eau — état écologique",date:"14 avril 2025",dataset:"qualite-de-leau-etat-ecologique",file:"qualite_ecologique.geojson",group:"Milieux",color:"#20a06b",kind:"quality",count:"178 tronçons",active:true},
  {id:"stations",title:"Stations de mesure de qualité",date:"16 avril 2025",dataset:"stations-de-mesure-de-qualite-de-leau-1",file:"stations.geojson",group:"Mesure",color:"#e4794a",kind:"point",count:"17 stations",active:true},
  {id:"potable",title:"Qualité sanitaire de l’eau du robinet",date:"12 derniers mois",api:"https://hubeau.eaufrance.fr/api/v1/qualite_eau_potable/resultats_dis",group:"Qualité sanitaire",color:"#1f8d49",kind:"api-commune",count:"communes · contrôles ARS",active:false,producer:"Hub’Eau · ministère chargé de la Santé / ARS"},
  {id:"secheresse",title:"Zones d’alerte sécheresse",date:"28 mai 2024",dataset:"zones-dalerte-secheresse",file:"secheresse.geojson",group:"Ressource",color:"#b34000",kind:"polygon",count:"3 bassins",active:false},
  {id:"ruissellement",title:"Axes de ruissellement",date:"21 septembre 2021",dataset:"axes-de-ruissellements",file:"axes-ruissellement.geojson",group:"Risques",color:"#e1000f",kind:"line",count:"2 049 axes",active:false},
  {id:"prix",title:"Prix de l’eau potable",date:"4 avril 2025",dataset:"eau-potable-prix-sur-la-base-dune-consommation-annuelle-de-120m3-1",file:"prix_eau.geojson",group:"Services publics",color:"#7a5af8",kind:"price",count:"151 valeurs",active:false},
  {id:"syndicats-eau",title:"Syndicats d’eau potable",date:"1 juillet 2025",dataset:"l-si-eau-potable-s-095-1",file:"syndicats_eau.geojson",group:"Gouvernance",color:"#0078f3",kind:"polygon",count:"23 syndicats",active:false},
  {id:"syndicats-assain",title:"Syndicats d’assainissement",date:"4 février 2025",dataset:"syndicats-dassainissement-val-doise",file:"syndicats_assainissement.geojson",group:"Gouvernance",color:"#8146a1",kind:"polygon",count:"194 territoires",active:false},
  {id:"syndicats-riviere",title:"Syndicats de rivière",date:"22 février 2025",dataset:"l-si-riviere-s-095",file:"syndicats_riviere.geojson",group:"Gouvernance",color:"#00a7b5",kind:"polygon",count:"183 communes",active:false},
  {id:"police",title:"Compétence police de l’eau",date:"1 avril 2025",dataset:"la-competence-police-de-leau",file:"police_eau.geojson",group:"Réglementation",color:"#d13c72",kind:"line",count:"1 549 tronçons",active:false},
  {id:"sup-as1",title:"SUP AS1 · protection des eaux",date:"référentiel national",dataset:"sup-as1-perimetres-de-protections-liees-aux-servitudes-de-la-categorie-as1-protection-des-eaux-1",file:null,group:"Servitudes",color:"#000091",kind:"unavailable",count:"Fiche DDT 95 référencée",active:false},
  {id:"sup-a5",title:"SUP A5 · canalisations d’eau et d’assainissement",date:"référentiel national",url:"https://www.geoportail-urbanisme.gouv.fr/services/",file:null,group:"Servitudes",color:"#6a6af4",kind:"unavailable",count:"Source Géoportail de l’urbanisme",active:false,producer:"Géoportail de l’urbanisme"},
  {id:"assain-prix",title:"Prix de l’assainissement collectif",date:"4 avril 2025",dataset:"assainissement-collectif-prix-associe-a-la-collecte-au-transport-et-au-traitement-des-eaux-usees",file:null,group:"Services publics",color:"#68737d",kind:"unavailable",count:"Service source indisponible",active:false},
  {id:"hydro-live",title:"Stations hydrométriques",date:"temps quasi réel",api:"https://hubeau.eaufrance.fr/api/v2/hydrometrie/referentiel/stations?code_departement=95&size=200&format=json",group:"Hub’Eau · mesures",color:"#0099c6",kind:"api-point",count:"17 stations",active:false,producer:"Hub’Eau · Vigicrues"},
  {id:"river-live",title:"Stations de qualité des rivières",date:"référentiel national",api:"https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/station_pc?code_departement=95&size=500&format=json",snapshot:"hubeau-river-stations.geojson",group:"Hub’Eau · mesures",color:"#009081",kind:"api-point",count:"56 stations",active:false,producer:"Hub’Eau · Naïades"},
  {id:"groundwater",title:"Points de qualité des nappes",date:"synchronisation continue",api:"https://hubeau.eaufrance.fr/api/v1/qualite_nappes/stations?num_departement=95&size=500&format=json",snapshot:"hubeau-groundwater-stations.geojson",group:"Hub’Eau · mesures",color:"#6a4c93",kind:"api-point",count:"451 points",active:false,producer:"Hub’Eau · ADES"},
  {id:"fish",title:"Stations d’inventaires piscicoles",date:"plus de 50 ans d’observations",api:"https://hubeau.eaufrance.fr/api/v1/etat_piscicole/stations?code_departement=95&size=200",snapshot:"hubeau-fish-stations.geojson",group:"Biodiversité",color:"#18753c",kind:"api-point",count:"38 stations",active:false,producer:"Hub’Eau · OFB / ASPE"},
  {id:"hydrobio",title:"Stations hydrobiologiques",date:"référentiel Naïades",api:"https://hubeau.eaufrance.fr/api/v1/hydrobio/stations_hydrobio?code_departement=95&size=200",snapshot:"hubeau-hydrobio-stations.geojson",group:"Biodiversité",color:"#c43c7a",kind:"api-point",count:"59 stations",active:false,producer:"Hub’Eau · Naïades"},
  {id:"etiage",title:"Débit des petits cours d’eau en été (Onde)",date:"dernières observations OFB",api:"https://hubeau.eaufrance.fr/api/v1/ecoulement/stations?code_departement=95&size=200",snapshot:"hubeau-etiage-stations.geojson",group:"Ressource",color:"#ce614a",kind:"api-point",count:"7 stations · écoulement, rupture ou assec",active:false,producer:"Hub’Eau · OFB / Onde"}
];

const themeGuide={
  cours:{short:"Où s’applique la réglementation « cours d’eau »",what:"Cette couche localise les tronçons reconnus comme cours d’eau par l’arrêté préfectoral.",read:"Elle indique le statut réglementaire du tronçon, son nom, son origine et les règles associées aux travaux ou traitements à proximité."},
  qualite:{short:"État écologique DCE des cours d’eau",what:"Elle classe les tronçons selon leur état écologique : bon, moyen, médiocre ou mauvais.",read:"La couleur résume l’état global du milieu aquatique. Ce classement combine des éléments biologiques, physico-chimiques et hydromorphologiques."},
  stations:{short:"pH, température, conductivité et prélèvements",what:"Ces stations servent au suivi physico-chimique des cours d’eau.",read:"Au clic, la fiche fournit notamment la station, le cours d’eau, la date du prélèvement, le pH, la température et la conductivité lorsque ces valeurs sont publiées."},
  potable:{short:"Contrôles sanitaires ARS par commune",what:"Cette couche synthétise les prélèvements de contrôle de l’eau distribuée au robinet sur les douze derniers mois.",read:"Vert : limites et références respectées. Orange : référence de qualité dépassée. Rouge : non-conformité sanitaire. La fiche détaille chaque paramètre, sa valeur, son unité et son seuil."},
  secheresse:{short:"Bassins utilisés pour déclencher les restrictions",what:"Les zones d’alerte sécheresse découpent le département en bassins de gestion de la ressource.",read:"Elles servent aux arrêtés de restriction. Cette couche montre le zonage de référence, pas à elle seule le niveau de restriction en vigueur."},
  ruissellement:{short:"Chemins préférentiels de l’eau de pluie",what:"Les axes représentent les trajectoires probables du ruissellement concentré selon la pente et le relief.",read:"Ils permettent d’identifier les secteurs exposés aux coulées de boue ou à l’arrivée rapide d’eau lors de fortes pluies. Ce ne sont pas des cours d’eau permanents."},
  prix:{short:"Prix communal pour une facture type de 120 m³",what:"La couche compare le tarif du service public d’eau potable sur la base réglementaire d’une consommation annuelle de 120 m³.",read:"Le montant est exprimé en euros par mètre cube. Il décrit le prix facturé, pas la qualité sanitaire de l’eau."},
  "syndicats-eau":{short:"Qui organise la production et la distribution",what:"Elle indique l’autorité organisatrice compétente pour l’eau potable dans chaque commune.",read:"La couleur différencie les syndicats. La fiche donne le nom, le SIREN et les communes couvertes lorsqu’ils sont renseignés."},
  "syndicats-assain":{short:"Qui gère collecte et traitement des eaux usées",what:"Elle cartographie les structures compétentes pour l’assainissement collectif ou non collectif.",read:"Elle permet d’identifier le service responsable selon la commune ; elle ne représente pas directement les réseaux enterrés."},
  "syndicats-riviere":{short:"Qui entretient et restaure les rivières",what:"Elle montre les syndicats intervenant sur les cours d’eau, les bassins versants et la compétence GEMAPI.",read:"Une commune peut relever de plusieurs syndicats selon les rivières ou bassins concernés ; la fiche énumère ces organismes."},
  police:{short:"Service compétent pour instruire la police de l’eau",what:"La couche associe chaque tronçon au service chargé de la police de l’eau.",read:"Elle renseigne l’organisation administrative du contrôle des travaux et usages ayant un impact sur les milieux aquatiques."},
  "sup-as1":{short:"Périmètres réglementaires de protection des eaux",what:"La servitude AS1 protège les captages d’eau destinée à la consommation humaine et certaines ressources minérales.",read:"Les périmètres peuvent imposer des interdictions ou prescriptions d’usage. La fiche officielle est référencée même lorsque sa géométrie n’est pas directement réutilisable."},
  "sup-a5":{short:"Servitudes liées aux canalisations publiques",what:"La servitude A5 concerne certaines canalisations publiques d’eau potable et d’assainissement.",read:"Elle peut encadrer l’accès, l’entretien et les constructions à proximité des ouvrages ; la source de référence est le Géoportail de l’urbanisme."},
  "assain-prix":{short:"Tarif de collecte et traitement des eaux usées",what:"Ce jeu décrit le prix du service d’assainissement collectif pour l’usager.",read:"Il complète le prix de l’eau potable. La ressource cartographique est conservée au catalogue même lorsque son téléchargement est indisponible."},
  "hydro-live":{short:"Hauteur et débit mesurés dans les rivières",what:"Les stations hydrométriques suivent en continu le niveau et, selon la station, le débit des cours d’eau.",read:"La fiche affiche la dernière hauteur brute disponible et son heure. Une hausse ou baisse doit être interprétée par rapport aux caractéristiques propres de la station."},
  "river-live":{short:"Analyses physico-chimiques des cours d’eau",what:"Ces stations centralisent les prélèvements de qualité des rivières : nutriments, oxygène, matières, micropolluants et autres paramètres publiés dans Naïades.",read:"La station localise le suivi. Les résultats varient selon les campagnes, les paramètres recherchés et les dates d’analyse."},
  groundwater:{short:"Analyses chimiques des nappes souterraines",what:"Ces points de suivi renseignent la qualité des eaux souterraines : nitrates, pesticides, minéraux et autres substances analysées.",read:"La fiche identifie le point, la masse d’eau, la profondeur et la période de mesure. La présence d’un point ne signifie pas qu’il alimente le réseau potable."},
  fish:{short:"Espèces et peuplements observés par pêche scientifique",what:"Les stations piscicoles correspondent à des opérations de pêche électrique menées par l’OFB et ses partenaires.",read:"Les observations permettent de connaître les espèces présentes, les effectifs et les tailles, puis d’évaluer l’état des peuplements dans le temps."},
  hydrobio:{short:"Invertébrés, diatomées, macrophytes et poissons",what:"Le suivi hydrobiologique observe les organismes vivant dans les cours d’eau et calcule des indices biologiques.",read:"Ces communautés réagissent à la pollution et à la dégradation des habitats ; leur composition renseigne donc la qualité écologique sur une période plus longue qu’une mesure ponctuelle."},
  etiage:{short:"Présence ou absence d’écoulement en période sèche",what:"Le réseau Onde suit visuellement les petits cours d’eau en été, notamment là où il n’existe pas de station de débit automatique.",read:"L’observation distingue l’écoulement visible, l’écoulement faible, la rupture d’écoulement et l’assec. Elle aide à repérer la tension sur la ressource et les milieux aquatiques."}
};

const state = {data:{},layers:{},charts:[],communes:null,territory:null,mask:null,basemap:"plan",legendId:null,potableAgg:null,detailToken:0};
const map = L.map("map",{zoomControl:false,preferCanvas:true,minZoom:8,maxZoom:18}).fitBounds(BOUNDS_95);
L.control.zoom({position:"bottomright"}).addTo(map);
L.control.scale({imperial:false,position:"bottomright"}).addTo(map);
const baseLayers={
  plan:L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,className:"neutral-tiles",attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> · Données DDT 95'}).addTo(map),
  ortho:L.tileLayer("https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image/jpeg",{maxZoom:19,attribution:"Photographies aériennes · IGN"})
};

function sourceUrl(s){return `https://www.data.gouv.fr/datasets/${s.dataset}`}
function externalSourceUrl(s){if(s.dataset)return sourceUrl(s);if(s.url)return s.url;return ({potable:"https://hubeau.eaufrance.fr/page/api-qualite-eau-potable","hydro-live":"https://hubeau.eaufrance.fr/page/api-hydrometrie","river-live":"https://hubeau.eaufrance.fr/page/api-qualite-cours-deau",groundwater:"https://hubeau.eaufrance.fr/page/api-qualite-nappes",fish:"https://hubeau.eaufrance.fr/page/api-poisson",hydrobio:"https://hubeau.eaufrance.fr/page/api-hydrobiologie",etiage:"https://hubeau.eaufrance.fr/page/api-ecoulement"})[s.id]||"https://hubeau.eaufrance.fr/page/apis"}
function safe(v){return v===null||v===undefined||v===""?"Non renseigné":String(v)}
function htmlSafe(v){return safe(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function monthsAgo(n){const d=new Date();d.setMonth(d.getMonth()-n);return d.toISOString().slice(0,10)}
function niceKey(k){return k.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
const categoryPalette=["#000091","#e1000f","#009081","#a558a0","#ce614a","#6a6af4","#18753c","#c3992a","#0078f3","#d13c72","#00a7b5","#7a5af8","#b34000","#0063cb","#ca8a04","#0f766e","#be123c","#4d7c0f","#9333ea","#ea580c","#0284c7","#db2777","#64748b","#15803d"];
const categoryColorMaps={};
function categoryColor(value,sourceId="global"){const s=String(value||"Non renseigné");const map=categoryColorMaps[sourceId]??=(new Map());if(!map.has(s))map.set(s,categoryPalette[map.size%categoryPalette.length]);return map.get(s)}
function categoryValue(source,p){if(source.id==="police")return p.POLICE_EAU||p["POLICE EAU"];if(source.id==="secheresse")return p.LbZAS||p.MnZAS;if(source.id==="syndicats-eau")return p.NOM_SI;if(source.id==="syndicats-assain")return p.DONNEES__1;if(source.id==="syndicats-riviere")return p.Syndic_RIV||p.SI_RIV;return null}
function layerStyle(source,feature){
  if(source.kind==="quality"){const c=qualityColors[String(feature.properties.etateco)]||qualityColors.U;return {color:c,weight:4,opacity:.9}}
  if(source.kind==="price"){const v=Number(feature.properties.TARIF_AEP);const c=!v?"#b9c0c7":v<2.5?"#d9d4f5":v<3?"#9b8cdc":v<4?"#6554c0":"#3f2c80";return {color:"#fff",weight:.6,fillColor:c,fillOpacity:.68}}
  if(source.kind==="polygon"){const c=categoryColor(categoryValue(source,feature.properties),source.id);return {color:c,weight:1.5,fillColor:c,fillOpacity:.25}}
  if(source.id==="police"){const c=categoryColor(categoryValue(source,feature.properties),source.id);return {color:c,weight:3,opacity:.9}}
  return {color:source.color,weight:source.id==="cours"?2.2:2,opacity:.84};
}
function displayTitle(source,p){
  return p.libelle_station||p.libelle_station_hydrobio||p.libelle_pe||p.LbStationM||p.NOM_SI||p.DONNEES__1||p.LbZAS||p.name||p.Nom||p.NOM||p.NomCoursdE||p["POLICE EAU"]||source.title;
}
function relevantProps(source,p){
  const preferred={stations:["CdStationM","LbStationM","NomCoursdE","LbCommune","pH","Temp","Conducti","DatePrelev"],cours:["NOM","ETAT","ZNT","BCAE","ORIGINE1"],qualite:["name","etateco","annee","longueur","statut"],prix:["NOM","INSEE_COM","TARIF_AEP","POPULATION"],secheresse:["LbZAS","TypeZAS","MnZAS"],"syndicats-eau":["NOM","NOM_SI","SIREN_SI","INSEE_COM"],"syndicats-assain":["NOM","DONNEES__1","DONNEES_SI","INSEE_COM"],"syndicats-riviere":["NOM","NB_Syndic","Syndic_RIV","SI_RIV","SI_RIV_2","SI_RIV_3","INSEE_COM","SIREN_EPCI"],police:["NOM","POLICE_EAU","NOM_2","ID_COURSDE"],"hydro-live":["code_station","libelle_cours_eau","libelle_commune","en_service","date_ouverture_station","date_fermeture_station","qualification_donnees_station"],"river-live":["code_station","nom_cours_eau","libelle_commune","nom_masse_deau","localisation_precise","date_creation","date_arret"],groundwater:["bss_id","code_bss","nom_commune","nom_nature_pe","nom_etat_pe","date_debut_mesure","date_fin_mesure","profondeur_investigation","noms_masse_eau_edl"],etiage:["code_station","libelle_cours_eau","libelle_commune","etat_station"]};
  return (preferred[source.id]||Object.keys(p).slice(0,8)).filter(k=>p[k]!==null&&p[k]!=="").map(k=>[k,p[k]]);
}
function openFeature(source,feature,clickedLatLng){
  const detailToken=++state.detailToken;
  const p=feature.properties||{}; const title=displayTitle(source,p);
  const cards=relevantProps(source,p).map(([k,v])=>`<div class="property"><small>${niceKey(k)}</small><strong>${k==="etateco"?(qualityLabels[String(v)]||v):safe(v)}${k==="TARIF_AEP"?" €/m³":""}</strong></div>`).join("");
  const guide=themeGuide[source.id];document.getElementById("detailContent").innerHTML=`<span class="detail-tag">${source.group} · ${source.producer||"DDT 95"}</span><h2>${safe(title)}</h2><p class="subtitle">${source.title} · ${source.date}</p>${guide?`<section class="theme-explainer"><strong>Ce que montre cette donnée</strong><p>${guide.what}</p><small>${guide.read}</small></section>`:""}<div id="liveDetail"></div><div class="property-grid">${cards}</div><a class="source-link" target="_blank" rel="noopener" href="${externalSourceUrl(source)}">Consulter la source officielle ↗</a>`;
  document.getElementById("detailPanel").classList.add("open");
  if(source.id==="hydro-live"&&p.code_station)loadLatestHydro(p.code_station);
  if(source.id==="etiage"&&p.code_station)loadLatestEtiage(p.code_station);
  if(source.id==="fish"&&p.code_station)loadFishData(p.code_station);
  if(source.id==="hydrobio"&&p.code_station_hydrobio)loadHydrobioData(p.code_station_hydrobio);
  if(source.id==="river-live"&&p.code_station)loadRiverQualityData(p.code_station);
  if(source.id==="groundwater"&&p.bss_id)loadGroundwaterData(p.bss_id);
  if(source.id==="cours"||source.id==="qualite")loadRiverProfile(title,feature,clickedLatLng,detailToken);
}
async function loadLatestHydro(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Recherche de la dernière mesure disponible…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v2/hydrometrie/observations_tr?code_entite=${encodeURIComponent(code)}&grandeur_hydro=H&size=1&fields=code_station,date_obs,resultat_obs,grandeur_hydro`;const r=await fetch(u);const d=await r.json();const o=d.data?.[0];box.innerHTML=o?`<div class="property live-property"><small>DERNIÈRE HAUTEUR DISPONIBLE</small><strong>${(Number(o.resultat_obs)/1000).toLocaleString("fr-FR",{maximumFractionDigits:3})} m</strong><span>${new Date(o.date_obs).toLocaleString("fr-FR")} · mesure brute Hub’Eau</span></div>`:'<p class="subtitle">Aucune hauteur récente disponible pour cette station.</p>'}catch(e){box.innerHTML='<p class="subtitle">La mesure temps réel n’est pas disponible actuellement.</p>'}}
async function loadLatestEtiage(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des observations visuelles OFB…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/ecoulement/observations?code_station=${encodeURIComponent(code)}&size=12`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const rows=(d.data||[]).sort((a,b)=>new Date(b.date_observation)-new Date(a.date_observation));const latest=rows[0];if(!latest){box.innerHTML='<p class="subtitle">Aucune observation publiée pour cette station.</p>';return}const codeEtat=String(latest.code_ecoulement||"");const level=codeEtat.startsWith("1")?"good":codeEtat.startsWith("2")?"warning":codeEtat.startsWith("3")?"danger":"unknown";const meaning=codeEtat.startsWith("1")?"L’eau circule encore dans le lit du cours d’eau.":codeEtat.startsWith("2")?"L’écoulement est interrompu par endroits : le cours d’eau devient vulnérable.":codeEtat.startsWith("3")?"Le lit est à sec sur la station : la situation est critique pour les milieux aquatiques.":"Observation visuelle réalisée par l’Office français de la biodiversité.";box.innerHTML=`<section class="flow-explainer"><span>À QUOI ÇA SERT ?</span><p>Le réseau Onde suit visuellement les petits cours d’eau pendant les périodes sèches. Il permet de repérer une baisse anormale de l’écoulement avant ou pendant une sécheresse.</p></section><section class="flow-status ${level}"><small>DERNIÈRE OBSERVATION · ${new Date(latest.date_observation).toLocaleDateString("fr-FR")}</small><strong>${htmlSafe(latest.libelle_ecoulement)}</strong><p>${meaning}</p></section><div class="flow-history"><strong>Historique récent</strong>${rows.slice(0,6).map(o=>`<div><time>${new Date(o.date_observation).toLocaleDateString("fr-FR")}</time><span>${htmlSafe(o.libelle_ecoulement)}</span></div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les observations Onde sont momentanément indisponibles.</p>'}}
async function loadFishData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des espèces et effectifs observés…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/etat_piscicole/observations?code_station=${encodeURIComponent(code)}&size=20000`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const all=d.data||[];if(!all.length){box.innerHTML='<p class="subtitle">Aucune observation piscicole publiée pour cette station.</p>';return}all.sort((a,b)=>new Date(b.date_operation)-new Date(a.date_operation));const lastDate=all[0].date_operation;const rows=all.filter(x=>x.date_operation===lastDate);const species={};rows.forEach(x=>{const n=x.nom_commun_taxon||x.nom_latin_taxon||"Taxon non renseigné";const a=species[n]??={effectif:0,min:null,max:null,latin:x.nom_latin_taxon};a.effectif+=Number(x.effectif_lot||1);if(Number.isFinite(Number(x.taille_min_lot)))a.min=a.min===null?Number(x.taille_min_lot):Math.min(a.min,Number(x.taille_min_lot));if(Number.isFinite(Number(x.taille_max_lot)))a.max=a.max===null?Number(x.taille_max_lot):Math.max(a.max,Number(x.taille_max_lot))});const list=Object.entries(species).sort((a,b)=>b[1].effectif-a[1].effectif);box.innerHTML=`<section class="data-summary"><strong>Dernière pêche scientifique · ${new Date(lastDate).toLocaleDateString("fr-FR")}</strong><span>${list.length} espèce(s) · ${list.reduce((n,[,x])=>n+x.effectif,0).toLocaleString("fr-FR")} individu(s) ou effectifs de lots publiés</span><small>${htmlSafe(rows[0].protocole_peche||"Protocole non renseigné")}</small></section><div class="analysis-list">${list.map(([name,x])=>`<div class="analysis-row"><span><b>${htmlSafe(name)}</b>${x.latin&&x.latin!==name?`<small>${htmlSafe(x.latin)}</small>`:""}</span><strong>${x.effectif.toLocaleString("fr-FR")}</strong>${x.min!==null||x.max!==null?`<small>Taille observée : ${x.min??"—"} à ${x.max??"—"} mm</small>`:""}</div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les observations piscicoles sont momentanément indisponibles.</p>'}}
async function loadHydrobioData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des indices biologiques mesurés…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/hydrobio/indices?code_station_hydrobio=${encodeURIComponent(code)}&size=5000`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const all=d.data||[];if(!all.length){box.innerHTML='<p class="subtitle">Aucun indice biologique publié pour cette station.</p>';return}all.sort((a,b)=>new Date(b.date_prelevement)-new Date(a.date_prelevement));const lastDate=all[0].date_prelevement;const rows=all.filter(x=>x.date_prelevement===lastDate);const supports=[...new Set(rows.map(x=>x.libelle_support).filter(Boolean))];box.innerHTML=`<section class="data-summary"><strong>Dernier prélèvement biologique · ${new Date(lastDate).toLocaleDateString("fr-FR")}</strong><span>${rows.length} indice(s) · ${htmlSafe(supports.join(", ")||"support non renseigné")}</span><small>Ces indices décrivent la diversité, l’abondance et la sensibilité des organismes à la dégradation du milieu.</small></section><div class="analysis-list">${rows.map(x=>`<div class="analysis-row"><span>${htmlSafe(x.libelle_indice)}</span><strong>${Number(x.resultat_indice).toLocaleString("fr-FR")} ${htmlSafe(x.unite_indice||"")}</strong><small>${htmlSafe(x.libelle_support||"")} · donnée ${htmlSafe(x.libelle_qualification||"non qualifiée")}</small></div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les indices hydrobiologiques sont momentanément indisponibles.</p>'}}
async function loadRiverQualityData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des dernières analyses de la rivière…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_station=${encodeURIComponent(code)}&date_debut_prelevement=${monthsAgo(18)}&size=5000`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const all=d.data||[];if(!all.length){box.innerHTML='<p class="subtitle">Aucune analyse publiée sur les 18 derniers mois.</p>';return}all.sort((a,b)=>new Date(b.date_prelevement)-new Date(a.date_prelevement));const lastDate=all[0].date_prelevement;const rows=all.filter(x=>x.date_prelevement===lastDate);box.innerHTML=`<section class="data-summary"><strong>Dernier prélèvement · ${new Date(lastDate).toLocaleDateString("fr-FR")}</strong><span>${rows.length} paramètre(s) analysé(s)</span><small>Eau, sédiments ou autre support : le support est précisé pour chaque résultat.</small></section><div class="analysis-list">${rows.map(x=>`<div class="analysis-row"><span>${htmlSafe(x.libelle_parametre)}</span><strong>${Number(x.resultat).toLocaleString("fr-FR")} ${htmlSafe(x.symbole_unite||"")}</strong><small>${htmlSafe(x.libelle_support||"")} · ${htmlSafe(x.mnemo_remarque||x.libelle_qualification||"")}</small></div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les analyses de la rivière sont momentanément indisponibles.</p>'}}
async function loadGroundwaterData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des analyses de la nappe…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/qualite_nappes/analyses?bss_id=${encodeURIComponent(code)}&size=5000`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const all=d.data||[];if(!all.length){box.innerHTML='<p class="subtitle">Aucune analyse publiée pour ce point.</p>';return}all.sort((a,b)=>new Date(b.date_debut_prelevement)-new Date(a.date_debut_prelevement));const lastDate=all[0].date_debut_prelevement;const rows=all.filter(x=>x.date_debut_prelevement===lastDate);box.innerHTML=`<section class="data-summary"><strong>Dernier prélèvement · ${new Date(lastDate).toLocaleDateString("fr-FR")}</strong><span>${rows.length} paramètre(s) analysé(s)</span><small>Les mentions « inférieur au seuil » signifient que la substance n’a pas été quantifiée au-dessus de la capacité de mesure du laboratoire.</small></section><div class="analysis-list">${rows.map(x=>`<div class="analysis-row"><span>${htmlSafe(x.nom_param)}</span><strong>${Number(x.resultat).toLocaleString("fr-FR")} ${htmlSafe(x.symbole_unite||"")}</strong><small>${htmlSafe(x.nom_remarque_analyse||x.nom_qualification||"")}</small></div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les analyses de la nappe sont momentanément indisponibles.</p>'}}
function normRiver(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\b(le|la|les|l|ru|rivière|riviere|cours|eau)\b/g," ").replace(/[^a-z0-9]+/g," ").trim()}
function pointOf(feature){const g=feature?.geometry;if(!g)return null;let c=g.coordinates;while(Array.isArray(c?.[0]))c=c[Math.floor(c.length/2)];return Array.isArray(c)&&Number.isFinite(c[0])&&Number.isFinite(c[1])?{lng:c[0],lat:c[1]}:null}
function distanceKm(a,b){const rad=Math.PI/180,dLat=(b.lat-a.lat)*rad,dLon=(b.lng-a.lng)*rad,x=Math.sin(dLat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function bestStation(features,latlng,riverName,fields){const target=normRiver(riverName);let ranked=(features||[]).map(f=>{const p=f.properties||f;const pt=pointOf(f)||((Number.isFinite(p.longitude)&&Number.isFinite(p.latitude))?{lng:p.longitude,lat:p.latitude}:null);if(!pt)return null;const names=fields.map(k=>normRiver(p[k])).filter(Boolean);const exact=target&&names.some(n=>n===target||n.includes(target)||target.includes(n));return {feature:f,km:distanceKm(latlng,pt),exact}}).filter(Boolean);ranked.sort((a,b)=>(b.exact-a.exact)||(a.km-b.km));return ranked[0]||null}
function riverMetric(label,value,unit,note){return `<div class="river-metric"><small>${label}</small><strong>${value??"—"}${value!==null&&value!==undefined&&unit?` ${unit}`:""}</strong>${note?`<span>${note}</span>`:""}</div>`}
async function loadRiverProfile(riverName,feature,clickedLatLng,token){const box=document.getElementById("liveDetail");if(!box)return;const fallback=pointOf(feature);const here=clickedLatLng||fallback;if(!here)return;box.innerHTML='<section class="river-loading">Construction du portrait de la rivière à partir des réseaux DDT 95, Naïades, Vigicrues et Onde…</section>';try{
  await Promise.all(["river-live","hydro-live","etiage"].map(id=>loadSource(sources.find(s=>s.id===id))));if(token!==state.detailToken)return;
  const qualityMatch=bestStation(state.data["river-live"]?.features,here,riverName,["nom_cours_eau","libelle_station"]);const hydroMatch=bestStation(state.data["hydro-live"]?.features,here,riverName,["libelle_cours_eau","libelle_station"]);const ondeMatch=bestStation(state.data.etiage?.features,here,riverName,["libelle_cours_eau","libelle_station"]);
  const ecoFeatures=state.data.qualite?.features||[];const eco=ecoFeatures.find(f=>{const n=normRiver(f.properties?.name);const t=normRiver(riverName);return n&&t&&(n===t||n.includes(t)||t.includes(n))});
  const qp=qualityMatch?.feature.properties;const hp=hydroMatch?.feature.properties;const op=ondeMatch?.feature.properties;
  const requests=[];
  requests.push(qp&&(qualityMatch.exact||qualityMatch.km<8)?fetch(`https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_station=${encodeURIComponent(qp.code_station)}&date_debut_prelevement=${monthsAgo(18)}&size=5000`).then(r=>r.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}));
  requests.push(hp&&(hydroMatch.exact||hydroMatch.km<10)?fetch(`https://hubeau.eaufrance.fr/api/v2/hydrometrie/observations_tr?code_entite=${encodeURIComponent(hp.code_station)}&grandeur_hydro=H&size=1`).then(r=>r.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}));
  requests.push(hp&&(hydroMatch.exact||hydroMatch.km<10)?fetch(`https://hubeau.eaufrance.fr/api/v2/hydrometrie/observations_tr?code_entite=${encodeURIComponent(hp.code_station)}&grandeur_hydro=Q&size=1`).then(r=>r.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}));
  requests.push(op&&(ondeMatch.exact||ondeMatch.km<8)?fetch(`https://hubeau.eaufrance.fr/api/v1/ecoulement/observations?code_station=${encodeURIComponent(op.code_station)}&size=1`).then(r=>r.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}));
  const [qualityJson,heightJson,flowJson,ondeJson]=await Promise.all(requests);if(token!==state.detailToken)return;
  const analyses=(qualityJson.data||[]).sort((a,b)=>new Date(b.date_prelevement)-new Date(a.date_prelevement));const lastQualityDate=analyses[0]?.date_prelevement;const latestAnalyses=lastQualityDate?analyses.filter(x=>x.date_prelevement===lastQualityDate):[];const h=heightJson.data?.[0],q=flowJson.data?.[0],onde=ondeJson.data?.[0];const ecoCode=String(eco?.properties?.etateco||"U");
  const qualityRows=latestAnalyses.slice(0,20).map(x=>`<div class="analysis-row"><span>${htmlSafe(x.libelle_parametre)}</span><strong>${Number(x.resultat).toLocaleString("fr-FR")} ${htmlSafe(x.symbole_unite||"")}</strong><small>${htmlSafe(x.libelle_support||"")} · ${htmlSafe(x.mnemo_remarque||x.libelle_qualification||"")}</small></div>`).join("");
  box.innerHTML=`<section class="river-profile"><div class="river-profile-head"><span>PORTRAIT MULTISOURCE</span><strong>${htmlSafe(riverName)}</strong><small>Données rapprochées du point cliqué ; la distance à chaque station est indiquée.</small></div><div class="river-metrics">${riverMetric("État écologique",qualityLabels[ecoCode]||"Non classé","",eco?.properties?.annee?`Millésime ${eco.properties.annee}`:"Couche DDT 95")}${riverMetric("Hauteur récente",h?(Number(h.resultat_obs)/1000).toLocaleString("fr-FR",{maximumFractionDigits:3}):null,"m",h?`${new Date(h.date_obs).toLocaleString("fr-FR")} · station à ${hydroMatch.km.toFixed(1)} km`:"Pas de station hydrométrique pertinente")}${riverMetric("Débit récent",q?(Number(q.resultat_obs)/1000).toLocaleString("fr-FR",{maximumFractionDigits:3}):null,"m³/s",q?`${new Date(q.date_obs).toLocaleString("fr-FR")} · mesure brute Vigicrues`:"Débit non disponible")}${riverMetric("Étiage Onde",onde?htmlSafe(onde.libelle_ecoulement):null,"",onde?`${new Date(onde.date_observation).toLocaleDateString("fr-FR")} · station à ${ondeMatch.km.toFixed(1)} km`:"Pas d’observation Onde pertinente")}</div>${qp?`<section class="river-source-line"><strong>Station qualité retenue</strong><span>${htmlSafe(qp.libelle_station||qp.nom_cours_eau)} · ${qualityMatch.km.toFixed(1)} km du clic</span></section>`:""}${latestAnalyses.length?`<section class="data-summary"><strong>Dernier prélèvement de qualité · ${new Date(lastQualityDate).toLocaleDateString("fr-FR")}</strong><span>${latestAnalyses.length} paramètre(s) publié(s) pour cette campagne</span><small>Les résultats ci-dessous sont des mesures de laboratoire ; ils ne constituent pas seuls le classement écologique global.</small></section><div class="analysis-list">${qualityRows}${latestAnalyses.length>20?`<div class="analysis-more">+ ${latestAnalyses.length-20} autres paramètres dans la source Hub’Eau</div>`:""}</div>`:'<p class="subtitle">Aucune analyse récente trouvée sur la station de qualité la plus pertinente.</p>'}</section>`;
}catch(e){if(token===state.detailToken)box.innerHTML='<p class="subtitle">Le portrait multisource de cette rivière est momentanément indisponible.</p>'}}
const potableColors={conforme:"#16a34a",vigilance:"#f59e0b",nonconforme:"#dc2626",nodata:"#94a3b8"};
function swatchBackground(source){
  if(source.kind==="quality")return `linear-gradient(90deg,${qualityColors["2"]} 0 25%,${qualityColors["3"]} 25% 50%,${qualityColors["4"]} 50% 75%,${qualityColors["5"]} 75%)`;
  if(source.kind==="price")return "linear-gradient(90deg,#d9d4f5 0 25%,#9b8cdc 25% 50%,#6554c0 50% 75%,#3f2c80 75%)";
  if(source.kind==="api-commune")return `linear-gradient(90deg,${potableColors.conforme} 0 33%,${potableColors.vigilance} 33% 66%,${potableColors.nonconforme} 66%)`;
  if(["police","syndicats-eau","syndicats-assain","syndicats-riviere","secheresse"].includes(source.id))return `linear-gradient(90deg,${categoryPalette.slice(0,6).map((c,i)=>`${c} ${i*100/6}% ${(i+1)*100/6}%`).join(",")})`;
  return source.color;
}
function potableStatus(rows){if(!rows.length)return "nodata";if(rows.some(r=>r.conformite_limites_bact_prelevement!=="C"||r.conformite_limites_pc_prelevement!=="C"))return "nonconforme";if(rows.some(r=>r.conformite_references_bact_prelevement!=="C"||r.conformite_references_pc_prelevement!=="C"))return "vigilance";return "conforme"}
async function loadPotableSource(source){
  if(!state.communes)await loadCommunes();
  const fields="code_commune,nom_commune,code_prelevement,date_prelevement,conclusion_conformite_prelevement,conformite_limites_bact_prelevement,conformite_limites_pc_prelevement,conformite_references_bact_prelevement,conformite_references_pc_prelevement,nom_distributeur,nom_moa";
  const url=`${source.api}?code_departement=95&code_parametre=1340&date_min_prelevement=${monthsAgo(12)}&size=5000&fields=${encodeURIComponent(fields)}`;
  const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(`Hub’Eau ${r.status}`);const d=await r.json();
  const byCommune={};const seen=new Set();(d.data||[]).forEach(x=>{if(!x.code_commune||seen.has(x.code_prelevement))return;seen.add(x.code_prelevement);(byCommune[x.code_commune]??=[]).push(x)});
  state.potableAgg={};Object.entries(byCommune).forEach(([code,rows])=>{rows.sort((a,b)=>new Date(b.date_prelevement)-new Date(a.date_prelevement));const lim=rows.filter(x=>x.conformite_limites_bact_prelevement==="C"&&x.conformite_limites_pc_prelevement==="C").length;const ref=rows.filter(x=>x.conformite_references_bact_prelevement==="C"&&x.conformite_references_pc_prelevement==="C").length;state.potableAgg[code]={rows,nb:rows.length,status:potableStatus(rows),tauxLimites:Math.round(lim/rows.length*1000)/10,tauxReferences:Math.round(ref/rows.length*1000)/10,dernier:rows[0]}});
  state.data[source.id]={type:"FeatureCollection",features:state.communes.features.map(f=>({type:"Feature",geometry:f.geometry,properties:{...f.properties,...(state.potableAgg[f.properties.code]||{status:"nodata",nb:0})}}))};
  state.layers[source.id]=L.geoJSON(state.data[source.id],{style:f=>({color:"#fff",weight:1,fillColor:potableColors[f.properties.status],fillOpacity:.68}),onEachFeature:(f,l)=>{l.bindTooltip(`${f.properties.nom} · ${f.properties.nb||0} prélèvement(s)`,{sticky:true});l.on("click",()=>openPotableDetail(f.properties.code,f.properties.nom,source))}});return state.layers[source.id]
}
async function openPotableDetail(code,nom,source){
  const agg=state.potableAgg?.[code]||{status:"nodata",nb:0};const labels={conforme:"Conforme",vigilance:"Dépassement d’une référence de qualité",nonconforme:"Non-conformité détectée",nodata:"Pas de prélèvement récent"};
  document.getElementById("detailContent").innerHTML=`<span class="detail-tag">QUALITÉ SANITAIRE · HUB’EAU / ARS</span><h2>${htmlSafe(nom)}</h2><div class="water-status ${agg.status}">${labels[agg.status]}</div><div class="property-grid"><div class="property"><small>PRÉLÈVEMENTS · 12 MOIS</small><strong>${agg.nb}</strong></div><div class="property"><small>CONFORMITÉ LIMITES</small><strong>${agg.tauxLimites??"—"} %</strong></div><div class="property"><small>CONFORMITÉ RÉFÉRENCES</small><strong>${agg.tauxReferences??"—"} %</strong></div><div class="property"><small>DERNIER CONTRÔLE</small><strong>${agg.dernier?.date_prelevement?new Date(agg.dernier.date_prelevement).toLocaleDateString("fr-FR"):"—"}</strong></div></div><div id="liveDetail"><p class="subtitle">Chargement de toutes les mesures du dernier contrôle…</p></div><a class="source-link" target="_blank" rel="noopener" href="${externalSourceUrl(source)}">Consulter l’API officielle ↗</a>`;document.getElementById("detailPanel").classList.add("open");
  if(!agg.dernier)return document.getElementById("liveDetail").innerHTML='<p class="subtitle">Aucune analyse récente publiée pour cette commune.</p>';
  try{const fields="code_prelevement,date_prelevement,libelle_parametre,resultat_alphanumerique,resultat_numerique,libelle_unite,limite_qualite_parametre,reference_qualite_parametre,conclusion_conformite_prelevement,nom_distributeur,nom_moa";const u=`${source.api}?code_prelevement=${encodeURIComponent(agg.dernier.code_prelevement)}&size=5000&fields=${encodeURIComponent(fields)}`;const r=await fetch(u,{cache:"no-store"});const d=await r.json();const rows=d.data||[];const intro=rows[0]||agg.dernier;document.getElementById("liveDetail").innerHTML=`<section class="analysis-summary"><strong>${htmlSafe(intro.conclusion_conformite_prelevement||"Conclusion non renseignée")}</strong><span>${rows.length} paramètres publiés · ${htmlSafe(intro.nom_moa||intro.nom_distributeur||"Gestionnaire non renseigné")}</span></section><div class="analysis-list">${rows.map(x=>`<div class="analysis-row"><span>${htmlSafe(x.libelle_parametre)}</span><strong>${htmlSafe(x.resultat_alphanumerique)} ${htmlSafe(x.libelle_unite||"")}</strong>${x.limite_qualite_parametre||x.reference_qualite_parametre?`<small>Seuil : ${htmlSafe(x.limite_qualite_parametre||x.reference_qualite_parametre)}</small>`:""}</div>`).join("")}</div>`}catch(e){document.getElementById("liveDetail").innerHTML='<p class="subtitle">Le détail des analyses est momentanément indisponible.</p>'}
}
async function loadSource(source){
  if(!source.file&&!source.api)return null;
  if(source.kind==="api-commune"&&!state.layers[source.id])return loadPotableSource(source);
  if(!state.data[source.id]){const local=source.snapshot||source.file;const r=await fetch(local?DATA_ROOT+local:source.api);if(!r.ok)throw new Error(`${source.title}: ${r.status}`);const d=await r.json();state.data[source.id]=local?d:{type:"FeatureCollection",features:(d.data||[]).filter(x=>x.geometry?.coordinates||Number.isFinite(x.longitude)&&Number.isFinite(x.latitude)).map(x=>({type:"Feature",properties:x,geometry:x.geometry?.coordinates?x.geometry:{type:"Point",coordinates:[x.longitude,x.latitude]}}))}}
  if(!state.layers[source.id]){
    state.layers[source.id]=L.geoJSON(state.data[source.id],{style:f=>layerStyle(source,f),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:7,color:"#fff",weight:2,fillColor:source.color,fillOpacity:1}),onEachFeature:(f,l)=>{l.on("click",e=>openFeature(source,f,e.latlng));l.bindTooltip(displayTitle(source,f.properties||{}),{sticky:true})}});
  }
  return state.layers[source.id];
}
async function setLayer(source,on){
  const control=document.getElementById(`layer-${source.id}`);
  if(source.kind==="unavailable"){control.checked=false;openFeature(source,{properties:{État:"La source officielle est référencée, mais aucune géométrie directement exploitable n’est actuellement publiée pour cette carte. Elle reste visible pour garantir la traçabilité du thème."}});return}
  control.disabled=true;if(on)document.getElementById("mapStatus").textContent=`Chargement : ${source.title}…`;
  try{const layer=await loadSource(source);if(on)layer.addTo(map);else map.removeLayer(layer);document.getElementById("mapStatus").textContent=on?`${source.title} affiché · ${source.count}`:"Couche retirée de la carte";if(on)renderLegend(source);else if(state.legendId===source.id)refreshLegend()}catch(e){if(state.layers[source.id])map.removeLayer(state.layers[source.id]);control.checked=false;refreshLegend();document.getElementById("mapStatus").textContent=`Impossible d’afficher cette couche : ${source.title}. Réessayez dans un instant.`;console.error(e)}finally{control.disabled=false}
}
function refreshLegend(){const active=[...sources].reverse().find(s=>document.getElementById(`layer-${s.id}`)?.checked&&state.layers[s.id]&&map.hasLayer(state.layers[s.id]));if(active)renderLegend(active);else{state.legendId=null;document.getElementById("mapLegend").innerHTML='<strong>Lecture de la carte</strong><span>Activez une couche pour afficher sa légende.</span>'}}
function renderLegend(source){const el=document.getElementById("mapLegend");let rows=[];
  if(source.kind==="quality")rows=Object.entries(qualityLabels).map(([k,v])=>[qualityColors[k],v]);
  else if(source.kind==="api-commune")rows=[[potableColors.conforme,"Conforme"],[potableColors.vigilance,"Référence dépassée"],[potableColors.nonconforme,"Non conforme"],[potableColors.nodata,"Sans donnée récente"]];
  else if(source.kind==="price")rows=[["#d9d4f5","moins de 2,50 €/m³"],["#9b8cdc","2,50 à 3 €/m³"],["#6554c0","3 à 4 €/m³"],["#3f2c80","4 €/m³ et plus"]];
  else if(["police","secheresse","syndicats-eau","syndicats-assain","syndicats-riviere"].includes(source.id)){const values=[...new Set((state.data[source.id]?.features||[]).map(f=>categoryValue(source,f.properties)).filter(Boolean))];rows=values.slice(0,7).map(v=>[categoryColor(v,source.id),v]);if(values.length>7)rows.push(["#68737d",`+ ${values.length-7} autres catégories`])}
  else rows=[[source.color,source.title]];
  state.legendId=source.id;el.innerHTML=`<strong>${source.title}</strong>${rows.map(([c,l])=>`<span><i style="background:${c}"></i>${l}</span>`).join("")}`;
}
function renderLayers(){
  const groups=[...new Set(sources.map(s=>s.group))]; const root=document.getElementById("layerList");
  root.innerHTML=groups.map(g=>`<section class="layer-group"><div class="group-title">${g}</div>${sources.filter(s=>s.group===g).map(s=>`<label class="layer-row" style="--layer-color:${s.color}"><input id="layer-${s.id}" type="checkbox" ${s.active?"checked":""} ${s.kind==="unavailable"?"aria-describedby='unavailable'":""}><span class="layer-label"><strong>${s.title}</strong><small>${s.count} · ${s.date}</small><span class="layer-help">${themeGuide[s.id]?.short||"Donnée cartographique"}</span></span><span class="legend-swatch ${s.kind.includes("point")?"point":""}" style="background:${swatchBackground(s)}"></span></label>`).join("")}</section>`).join("");
  sources.forEach(s=>document.getElementById(`layer-${s.id}`).addEventListener("change",e=>setLayer(s,e.target.checked)));
}
function renderSources(){document.getElementById("sourceCards").innerHTML=sources.map(s=>`<article class="source-card"><div><h3>${s.title}</h3><p>${themeGuide[s.id]?.what||"Donnée territoriale sur l’eau."}<br><b>Lecture :</b> ${themeGuide[s.id]?.read||"Consulter la fiche officielle."}<br>Producteur : ${s.producer||"Direction départementale des territoires du Val-d’Oise"} · ${s.date}</p><span class="source-status">${s.kind==="unavailable"?"Référencée · service indisponible":s.snapshot?"Référentiel local sécurisé · mesures via API":s.api?"Connectée à l’API":"Intégrée à l’observatoire"}</span></div><a href="${externalSourceUrl(s)}" target="_blank" rel="noopener">Ouvrir ↗</a></article>`).join("")}
async function loadCommunes(){try{const r=await fetch("https://geo.api.gouv.fr/departements/95/communes?fields=nom,code,centre,contour&format=geojson&geometry=contour");state.communes=await r.json();const holes=[];state.communes.features.forEach(f=>{const g=f.geometry;if(g.type==="Polygon")holes.push(g.coordinates[0]);else if(g.type==="MultiPolygon")g.coordinates.forEach(p=>holes.push(p[0]))});state.mask=L.geoJSON({type:"Feature",properties:{},geometry:{type:"Polygon",coordinates:[[[ -180,-85],[180,-85],[180,85],[-180,85],[-180,-85]],...holes]}},{interactive:false,className:"map-mask",style:{stroke:false,fillColor:"#e7ebf2",fillOpacity:.88,fillRule:"evenodd"}}).addTo(map);state.territory=L.geoJSON(state.communes,{interactive:false,style:{color:"#565b6c",weight:.7,opacity:.68,fillOpacity:0}}).addTo(map);map.fitBounds(state.territory.getBounds(),{padding:[28,28]});map.setMaxBounds(state.territory.getBounds().pad(.45))}catch(e){state.communes={features:[]}}}
async function search(){const q=document.getElementById("searchInput").value.trim();if(!q)return;const box=document.getElementById("searchResults");let items=[];
  if(state.communes)items=state.communes.features.filter(f=>f.properties.nom.toLowerCase().includes(q.toLowerCase())).slice(0,5).map(f=>{const c=L.geoJSON(f).getBounds().getCenter();return {label:f.properties.nom,coords:[c.lat,c.lng]}});
  if(!items.length){try{const r=await fetch(`https://data.geopf.fr/geocodage/search?q=${encodeURIComponent(q+" Val-d'Oise")}&limit=5`);const d=await r.json();items=(d.features||[]).map(f=>({label:f.properties.label,coords:[f.geometry.coordinates[1],f.geometry.coordinates[0]]}))}catch(e){}}
  box.innerHTML=items.length?items.map((x,i)=>`<button data-i="${i}">${x.label}</button>`).join(""):"<button>Aucun résultat dans le Val-d’Oise</button>";box.hidden=false;box.querySelectorAll("button[data-i]").forEach(b=>b.onclick=()=>{const x=items[+b.dataset.i];map.flyTo(x.coords,14);L.popup().setLatLng(x.coords).setContent(`<strong>${x.label}</strong>`).openOn(map);box.hidden=true})
}
function chartData(){
  const q=state.data.qualite?.features||[];const quality=Object.keys(qualityLabels).map(k=>q.filter(f=>String(f.properties.etateco)===k).length);
  const prices=(state.data.prix?.features||[]).map(f=>Number(f.properties.TARIF_AEP)).filter(Boolean);const bins=[0,0,0,0];prices.forEach(v=>bins[v<2.5?0:v<3?1:v<4?2:3]++);
  const station=state.data.stations?.features||[];const basins={};station.forEach(f=>{const k=f.properties.NomEuBassi||"Non renseigné";basins[k]=(basins[k]||0)+1});return {quality,prices,bins,basins};
}
function makeCharts(){state.charts.forEach(c=>c.destroy());const d=chartData();const common={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:"#edf1f3"}}}};
  state.charts.push(new Chart(document.getElementById("qualityChart"),{type:"bar",data:{labels:Object.values(qualityLabels),datasets:[{data:d.quality,backgroundColor:Object.values(qualityColors),borderWidth:0}]},options:{...common,indexAxis:"y"}}));
  state.charts.push(new Chart(document.getElementById("priceChart"),{type:"bar",data:{labels:["< 2,50 €","2,50–3 €","3–4 €","≥ 4 €"],datasets:[{data:d.bins,backgroundColor:"#6554c0",borderRadius:3}]},options:common}));
  state.charts.push(new Chart(document.getElementById("basinChart"),{type:"doughnut",data:{labels:Object.keys(d.basins),datasets:[{data:Object.values(d.basins),backgroundColor:["#0063cb","#00a7b5","#f49b2f","#8146a1"]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{boxWidth:10,font:{size:9}}}}}}));
  const good=d.quality[0]||0,total=d.quality.reduce((a,b)=>a+b,0),pct=Math.round(good/total*100);document.getElementById("insightValue").textContent=`${pct} %`;document.getElementById("insightText").textContent=`des tronçons qualifiés sont classés en bon état écologique. ${d.quality[1]||0} tronçons restent en état moyen.`
}
async function init(){renderLayers();renderSources();await Promise.all(sources.filter(s=>s.file).map(loadSource));await Promise.all(sources.filter(s=>s.active).map(s=>setLayer(s,true)));await loadCommunes();document.getElementById("mapStatus").textContent="10 couches DDT 95 prêtes · 7 connexions Hub’Eau disponibles"}
document.getElementById("searchButton").onclick=search;document.getElementById("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter")search()});document.getElementById("resetView").onclick=()=>state.territory?map.fitBounds(state.territory.getBounds(),{padding:[28,28]}):map.fitBounds(BOUNDS_95);document.getElementById("resetPanel").onclick=()=>document.getElementById("resetView").click();document.getElementById("closeDetail").onclick=()=>document.getElementById("detailPanel").classList.remove("open");document.getElementById("clearLayers").onclick=()=>sources.forEach(s=>{const e=document.getElementById(`layer-${s.id}`);if(e.checked){e.checked=false;setLayer(s,false)}});document.getElementById("openSources").onclick=()=>document.getElementById("sourcesDialog").showModal();document.getElementById("openDashboard").onclick=()=>{makeCharts();document.getElementById("dashboardDialog").showModal()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());document.querySelectorAll(".map-kpis button").forEach(b=>b.onclick=()=>{const s=sources.find(x=>x.id===b.dataset.focus);const e=document.getElementById(`layer-${s.id}`);if(!e.checked){e.checked=true;setLayer(s,true)}});document.querySelectorAll("[data-basemap]").forEach(b=>b.onclick=()=>{const id=b.dataset.basemap;if(id===state.basemap)return;map.removeLayer(baseLayers[state.basemap]);baseLayers[id].addTo(map);baseLayers[id].bringToBack();state.basemap=id;document.querySelectorAll("[data-basemap]").forEach(x=>x.classList.toggle("active",x===b))});
init();
