const BUILD_VERSION="20260805q";
fetch(`version.json?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(v=>{if(v.version!==BUILD_VERSION){const u=new URL(location.href);u.searchParams.set("v",v.version);location.replace(u)}}).catch(()=>{});
const DATA_ROOT = "data/processed/";
const BOUNDS_95 = [[48.89,1.60],[49.25,2.60]];
const qualityLabels = {"2":"Bon état","3":"État moyen","4":"État médiocre","5":"Mauvais état","U":"Non classé"};
const qualityColors = {"2":"#20a06b","3":"#f0c541","4":"#ee8b38","5":"#d94a4a","U":"#88959e"};
const groundwaterColors={FRHG001:"#0077b6",FRHG002:"#00a896",FRHG102:"#e07a2f",FRHG104:"#7b5cc7",FRHG107:"#c23b73",FRHG201:"#65752b",FRHG218:"#8a5a44"};

const sources = [
  {id:"cours",title:"Cours d’eau du Val-d’Oise — arrêté préfectoral",date:"18 février 2021",dataset:"cours-deau-du-val-doise-arrete-prefectoral-ndeg2017-13817-1",file:"cours_eau.geojson",group:"Milieux",color:"#0063cb",kind:"line",count:"1 425 tronçons",active:true},
  {id:"qualite",title:"Qualité de l’eau — état écologique",date:"14 avril 2025",dataset:"qualite-de-leau-etat-ecologique",file:"qualite_ecologique.geojson",group:"Milieux",color:"#20a06b",kind:"quality",count:"178 tronçons",active:true},
  {id:"stations",title:"Stations de mesure de qualité",date:"16 avril 2025",dataset:"stations-de-mesure-de-qualite-de-leau-1",file:"stations.geojson",group:"Mesure",color:"#e4794a",kind:"point",count:"17 stations",active:true},
  {id:"potable",title:"Qualité sanitaire de l’eau du robinet",date:"12 derniers mois",api:"https://hubeau.eaufrance.fr/api/v1/qualite_eau_potable/resultats_dis",group:"Qualité sanitaire",color:"#1f8d49",kind:"api-commune",count:"communes · contrôles ARS",active:false,producer:"Hub’Eau · ministère chargé de la Santé / ARS"},
  {id:"secheresse",title:"Zones d’alerte sécheresse",date:"28 mai 2024",dataset:"zones-dalerte-secheresse",file:"secheresse.geojson",group:"Ressource",color:"#b34000",kind:"polygon",count:"3 bassins",active:false},
  {id:"ruissellement",title:"Axes de ruissellement",date:"21 septembre 2021",dataset:"axes-de-ruissellements",file:"axes-ruissellement.geojson",group:"Risques",color:"#e1000f",kind:"line",count:"2 049 axes",active:false},
  {id:"prix",title:"Prix de l’eau potable",date:"4 avril 2025",dataset:"eau-potable-prix-sur-la-base-dune-consommation-annuelle-de-120m3-1",file:"prix_eau.geojson",group:"Services publics",color:"#7a5af8",kind:"price",count:"151 valeurs",active:false},
  {id:"syndicats-eau",title:"Syndicats d’eau potable",date:"1 juillet 2025",dataset:"l-si-eau-potable-s-095-1",file:"syndicats_eau.geojson",group:"Gouvernance",color:"#0078f3",kind:"polygon",count:"23 syndicats",active:false},
  {id:"syndicats-assain",title:"Syndicats d’assainissement",date:"4 février 2025",dataset:"syndicats-dassainissement-val-doise",file:"syndicats_assainissement.geojson",group:"Gouvernance",color:"#8146a1",kind:"polygon",count:"193 géométries · 194 enregistrements",active:false},
  {id:"syndicats-riviere",title:"Syndicats de rivière",date:"22 février 2025",dataset:"l-si-riviere-s-095",file:"syndicats_riviere.geojson",group:"Gouvernance",color:"#00a7b5",kind:"polygon",count:"183 communes",active:false},
  {id:"police",title:"Compétence police de l’eau",date:"1 avril 2025",dataset:"la-competence-police-de-leau",file:"police_eau.geojson",group:"Réglementation",color:"#d13c72",kind:"line",count:"1 549 tronçons",active:false},
  {id:"sup-as1",title:"SUP AS1 · protection des eaux",date:"référentiel national",dataset:"sup-as1-perimetres-de-protections-liees-aux-servitudes-de-la-categorie-as1-protection-des-eaux-1",file:null,group:"Servitudes",color:"#000091",kind:"unavailable",count:"Fiche DDT 95 référencée",active:false},
  {id:"sup-a5",title:"SUP A5 · canalisations d’eau et d’assainissement",date:"référentiel national",url:"https://www.geoportail-urbanisme.gouv.fr/services/",file:null,group:"Servitudes",color:"#6a6af4",kind:"unavailable",count:"Source Géoportail de l’urbanisme",active:false,producer:"Géoportail de l’urbanisme"},
  {id:"assain-prix",title:"Prix de l’assainissement collectif",date:"4 avril 2025",dataset:"assainissement-collectif-prix-associe-a-la-collecte-au-transport-et-au-traitement-des-eaux-usees",file:null,group:"Services publics",color:"#68737d",kind:"unavailable",count:"Service source indisponible",active:false},
  {id:"hydro-live",title:"Stations hydrométriques",date:"référentiel national",api:"https://hubeau.eaufrance.fr/api/v2/hydrometrie/referentiel/stations?code_departement=95&size=200&format=json",snapshot:"hubeau-hydro-stations.geojson",group:"Hub’Eau · mesures",color:"#0099c6",kind:"api-point",count:"9 stations dans le Val-d’Oise",active:false,producer:"Sandre · Hub’Eau / Vigicrues"},
  {id:"river-live",title:"Stations de qualité des rivières",date:"référentiel national",api:"https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/station_pc?code_departement=95&size=500&format=json",snapshot:"hubeau-river-stations.geojson",group:"Hub’Eau · mesures",color:"#009081",kind:"api-point",count:"56 stations",active:false,producer:"Hub’Eau · Naïades"},
  {id:"groundwater-bodies",title:"Masses d’eau souterraines",date:"rapportage DCE 2022",url:"https://www.sandre.eaufrance.fr/v2/news/diffusion-des-masses-d-eau-souterraines-du-rapportage-2022-au-format-sandre-sur-l-atals-catalogue",file:"groundwater-bodies.geojson",group:"Nappes phréatiques",color:"#4f46a5",kind:"groundwater-body",count:"7 masses · 4 horizons",active:false,producer:"Sandre · Eaufrance"},
  {id:"piezometers",title:"Niveau des nappes — piézomètres récents",date:"mesures ADES actualisées",url:"https://hubeau.eaufrance.fr/page/api-piezometrie",file:"piezometers-recent.geojson",group:"Nappes phréatiques",color:"#00849a",kind:"api-point",count:"6 stations suivies depuis 2025",active:false,producer:"Hub’Eau · ADES / BRGM"},
  {id:"groundwater",title:"Qualité chimique des nappes",date:"synchronisation continue",api:"https://hubeau.eaufrance.fr/api/v1/qualite_nappes/stations?num_departement=95&size=500&format=json",snapshot:"hubeau-groundwater-stations.geojson",group:"Nappes phréatiques",color:"#8b5fbf",kind:"api-point",count:"451 points historiques et actuels",active:false,producer:"Hub’Eau · ADES"},
  {id:"fish",title:"Stations d’inventaires piscicoles",date:"plus de 50 ans d’observations",api:"https://hubeau.eaufrance.fr/api/v1/etat_piscicole/stations?code_departement=95&size=200",snapshot:"hubeau-fish-stations.geojson",group:"Biodiversité",color:"#18753c",kind:"api-point",count:"38 stations",active:false,producer:"Hub’Eau · OFB / ASPE"},
  {id:"hydrobio",title:"Stations hydrobiologiques",date:"référentiel Naïades",api:"https://hubeau.eaufrance.fr/api/v1/hydrobio/stations_hydrobio?code_departement=95&size=200",snapshot:"hubeau-hydrobio-stations.geojson",group:"Biodiversité",color:"#c43c7a",kind:"api-point",count:"59 stations",active:false,producer:"Hub’Eau · Naïades"},
  {id:"etiage",title:"Débit des petits cours d’eau en été (Onde)",date:"dernières observations OFB",api:"https://hubeau.eaufrance.fr/api/v1/ecoulement/stations?code_departement=95&size=200",snapshot:"hubeau-etiage-stations.geojson",group:"Ressource",color:"#ce614a",kind:"api-point",count:"7 stations · écoulement, rupture ou assec",active:false,producer:"Hub’Eau · OFB / Onde"}
];

const themeGuide={
  cours:{short:"Où s’applique la réglementation « cours d’eau »",what:"Cette couche localise les tronçons reconnus comme cours d’eau par l’arrêté préfectoral.",read:"Elle indique le statut réglementaire du tronçon, son nom, son origine et les règles associées aux travaux ou traitements à proximité."},
  qualite:{short:"État écologique DCE des cours d’eau",what:"Elle classe les tronçons selon leur état écologique : bon, moyen, médiocre ou mauvais.",read:"La couleur résume l’état global du milieu aquatique. Ce classement combine des éléments biologiques, physico-chimiques et hydromorphologiques."},
  stations:{short:"pH, température, conductivité et prélèvements",what:"Ces stations servent au suivi physico-chimique des cours d’eau.",read:"Au clic, la fiche fournit notamment la station, le cours d’eau, la date du prélèvement, le pH, la température et la conductivité lorsque ces valeurs sont publiées."},
  potable:{short:"Contrôles sanitaires ARS par commune",what:"Cette couche synthétise les prélèvements de contrôle de l’eau distribuée au robinet sur les douze derniers mois.",read:"Vert : limites et références respectées. Orange : référence de qualité dépassée. Rouge : non-conformité sanitaire. La fiche détaille chaque paramètre, sa valeur, son unité et son seuil."},
  secheresse:{short:"Bassins utilisés pour déclencher les restrictions",what:"Les zones d’alerte sécheresse découpent le département en bassins de gestion de la ressource.",read:"Elles servent aux arrêtés de restriction. Cette couche montre le zonage de référence, pas à elle seule le niveau de restriction en vigueur."},
  ruissellement:{short:"Chemins préférentiels de l’eau de pluie",what:"Les axes représentent les trajectoires probables du ruissellement concentré selon la pente et le relief.",read:"Ils permettent d’identifier les secteurs exposés aux coulées de boue ou à l’arrivée rapide d’eau lors de fortes pluies. Ce ne sont pas des cours d’eau permanents."},
  prix:{short:"Prix communal pour une facture type de 120 m³",what:"La couche compare le tarif du service public d’eau potable sur la base réglementaire d’une consommation annuelle de 120 m³.",read:"Le montant est exprimé en euros par mètre cube. Il décrit le prix facturé, pas la qualité sanitaire de l’eau."},
  "syndicats-eau":{short:"Qui organise la production et la distribution",what:"Elle indique l’autorité organisatrice compétente pour l’eau potable dans chaque commune.",read:"La couleur différencie les syndicats. La fiche donne le nom, le SIREN et les communes couvertes lorsqu’ils sont renseignés."},
  "syndicats-assain":{short:"Qui gère collecte et traitement des eaux usées",what:"Elle cartographie les structures compétentes pour l’assainissement collectif ou non collectif.",read:"Elle permet d’identifier le service responsable selon la commune ; elle ne représente pas directement les réseaux enterrés."},
  "syndicats-riviere":{short:"Qui entretient et restaure les rivières",what:"Elle montre les syndicats intervenant sur les cours d’eau, les bassins versants et la compétence GEMAPI.",read:"Une commune peut relever de plusieurs syndicats selon les rivières ou bassins concernés ; la fiche énumère ces organismes."},
  police:{short:"Service compétent pour instruire la police de l’eau",what:"La couche associe chaque tronçon au service chargé de la police de l’eau.",read:"Elle renseigne l’organisation administrative du contrôle des travaux et usages ayant un impact sur les milieux aquatiques."},
  "sup-as1":{short:"Périmètres réglementaires de protection des eaux",what:"La servitude AS1 protège les captages d’eau destinée à la consommation humaine et certaines ressources minérales.",read:"Les périmètres peuvent imposer des interdictions ou prescriptions d’usage. La fiche officielle est référencée même lorsque sa géométrie n’est pas directement réutilisable."},
  "sup-a5":{short:"Servitudes liées aux canalisations publiques",what:"La servitude A5 concerne certaines canalisations publiques d’eau potable et d’assainissement.",read:"Elle peut encadrer l’accès, l’entretien et les constructions à proximité des ouvrages ; la source de référence est le Géoportail de l’urbanisme."},
  "assain-prix":{short:"Tarif de collecte et traitement des eaux usées",what:"Ce jeu décrit le prix du service d’assainissement collectif pour l’usager.",read:"Il complète le prix de l’eau potable. La ressource cartographique est conservée au catalogue même lorsque son téléchargement est indisponible."},
  "hydro-live":{short:"Hauteur et débit mesurés dans les rivières",what:"Les stations hydrométriques suivent en continu le niveau et, selon la station, le débit des cours d’eau.",read:"La fiche affiche la dernière hauteur brute disponible et son heure. Une hausse ou baisse doit être interprétée par rapport aux caractéristiques propres de la station."},
  "river-live":{short:"Analyses physico-chimiques des cours d’eau",what:"Ces stations centralisent les prélèvements de qualité des rivières : nutriments, oxygène, matières, micropolluants et autres paramètres publiés dans Naïades.",read:"La station localise le suivi. Les résultats varient selon les campagnes, les paramètres recherchés et les dates d’analyse."},
  "groundwater-bodies":{short:"Les aquifères présents sous le territoire",what:"Ces polygones représentent les masses d’eau souterraines utilisées pour l’évaluation de la Directive-cadre sur l’eau.",read:"L’horizon 1 est le niveau le plus proche de la surface ; les horizons 2 à 4 représentent des masses progressivement plus profondes. Plusieurs nappes peuvent donc se superposer au même endroit."},
  piezometers:{short:"Profondeur et cote du niveau de la nappe",what:"Un piézomètre est un forage d’observation qui mesure la hauteur de l’eau souterraine en un point précis.",read:"La fiche affiche la dernière cote en mètres NGF, la profondeur publiée, l’évolution récente et la nappe suivie. Six stations ont publié une mesure depuis 2025 dans le Val-d’Oise."},
  groundwater:{short:"Analyses chimiques des nappes souterraines",what:"Ces points de suivi renseignent la qualité des eaux souterraines : nitrates, pesticides, minéraux et autres substances analysées.",read:"La fiche identifie le point, la masse d’eau, la profondeur et la période de mesure. La présence d’un point ne signifie pas qu’il alimente le réseau potable."},
  fish:{short:"Espèces et peuplements observés par pêche scientifique",what:"Les stations piscicoles correspondent à des opérations de pêche électrique menées par l’OFB et ses partenaires.",read:"Les observations permettent de connaître les espèces présentes, les effectifs et les tailles, puis d’évaluer l’état des peuplements dans le temps."},
  hydrobio:{short:"Invertébrés, diatomées, macrophytes et poissons",what:"Le suivi hydrobiologique observe les organismes vivant dans les cours d’eau et calcule des indices biologiques.",read:"Ces communautés réagissent à la pollution et à la dégradation des habitats ; leur composition renseigne donc la qualité écologique sur une période plus longue qu’une mesure ponctuelle."},
  etiage:{short:"Présence ou absence d’écoulement en période sèche",what:"Le réseau Onde suit visuellement les petits cours d’eau en été, notamment là où il n’existe pas de station de débit automatique.",read:"L’observation distingue l’écoulement visible, l’écoulement faible, la rupture d’écoulement et l’assec. Elle aide à repérer la tension sur la ressource et les milieux aquatiques."}
};

const state = {data:{},layers:{},charts:[],communes:null,territory:null,mask:null,basemap:"plan",legendId:null,potableAgg:null,detailToken:0,groundwaterHorizon:1};
const map = L.map("map",{zoomControl:false,preferCanvas:true,minZoom:6,maxZoom:19,zoomSnap:.25,zoomDelta:.5}).fitBounds(BOUNDS_95,{padding:[8,8]});
map.createPane("maskPane");map.getPane("maskPane").style.zIndex=420;map.getPane("maskPane").style.pointerEvents="none";
map.createPane("boundaryPane");map.getPane("boundaryPane").style.zIndex=430;map.getPane("boundaryPane").style.pointerEvents="none";
L.control.zoom({position:"bottomright"}).addTo(map);
L.control.scale({imperial:false,position:"bottomright"}).addTo(map);
const baseLayers={
  plan:L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,className:"neutral-tiles",attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> · Données DDT 95'}).addTo(map),
  ortho:L.tileLayer("https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image/jpeg",{maxZoom:19,attribution:"Photographies aériennes · IGN"})
};

function sourceUrl(s){return `https://www.data.gouv.fr/datasets/${s.dataset}`}
function externalSourceUrl(s){if(s.dataset)return sourceUrl(s);if(s.url)return s.url;return ({potable:"https://hubeau.eaufrance.fr/page/api-qualite-eau-potable","hydro-live":"https://hubeau.eaufrance.fr/page/api-hydrometrie","river-live":"https://hubeau.eaufrance.fr/page/api-qualite-cours-deau",groundwater:"https://hubeau.eaufrance.fr/page/api-qualite-nappes",fish:"https://hubeau.eaufrance.fr/page/api-poisson",hydrobio:"https://hubeau.eaufrance.fr/page/api-hydrobiologie",etiage:"https://hubeau.eaufrance.fr/page/api-ecoulement"})[s.id]||"https://hubeau.eaufrance.fr/page/apis"}
function safe(v){return v===null||v===undefined||v===""?"Non renseigné":String(v)}
function htmlSafe(v){return safe(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c])}
function monthsAgo(n){const d=new Date();d.setMonth(d.getMonth()-n);return d.toISOString().slice(0,10)}
function niceKey(k){return k.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
const categoryPalette=["#000091","#e1000f","#009081","#a558a0","#ce614a","#6a6af4","#18753c","#c3992a","#0078f3","#d13c72","#00a7b5","#7a5af8","#b34000","#0063cb","#ca8a04","#0f766e","#be123c","#4d7c0f","#9333ea","#ea580c","#0284c7","#db2777","#64748b","#15803d"];
const categoryColorMaps={};
function categoryColor(value,sourceId="global"){const s=String(value||"Non renseigné");const map=categoryColorMaps[sourceId]??=(new Map());if(!map.has(s))map.set(s,categoryPalette[map.size%categoryPalette.length]);return map.get(s)}
function categoryValue(source,p){if(source.id==="police")return p.POLICE_EAU||p["POLICE EAU"];if(source.id==="secheresse")return p.LbZAS||p.MnZAS;if(source.id==="syndicats-eau")return p.NOM_SI;if(source.id==="syndicats-assain")return p.DONNEES__1;if(source.id==="syndicats-riviere")return p.Syndic_RIV||p.SI_RIV;return null}
function layerStyle(source,feature){
  if(source.kind==="quality"){const c=qualityColors[String(feature.properties.etateco)]||qualityColors.U;return {color:c,weight:4,opacity:.9}}
  if(source.kind==="groundwater-body"){const c=groundwaterColors[feature.properties.code]||source.color;return {color:c,weight:2,fillColor:c,fillOpacity:.42}}
  if(source.kind==="price"){const v=Number(feature.properties.TARIF_AEP);const c=!v?"#b9c0c7":v<2.5?"#d9d4f5":v<3?"#9b8cdc":v<4?"#6554c0":"#3f2c80";return {color:"#fff",weight:.6,fillColor:c,fillOpacity:.68}}
  if(source.kind==="polygon"){const c=categoryColor(categoryValue(source,feature.properties),source.id);return {color:c,weight:1.5,fillColor:c,fillOpacity:.25}}
  if(source.id==="police"){const c=categoryColor(categoryValue(source,feature.properties),source.id);return {color:c,weight:3,opacity:.9}}
  return {color:source.color,weight:source.id==="cours"?2.2:2,opacity:.84};
}
function displayTitle(source,p){
  return p.libelle_station||p.libelle_station_hydrobio||p.libelle_pe||p.nom||p.LbStationM||p.NOM_SI||p.DONNEES__1||p.LbZAS||p.name||p.Nom||p.NOM||p.NomCoursdE||p["POLICE EAU"]||source.title;
}
function relevantProps(source,p){
  const preferred={stations:["CdStationM","LbStationM","NomCoursdE","LbCommune","pH","Temp","Conducti","DatePrelev"],cours:["NOM","ETAT","ZNT","BCAE","ORIGINE1"],qualite:["name","etateco","annee","longueur","statut"],prix:["NOM","INSEE_COM","TARIF_AEP","POPULATION"],secheresse:["LbZAS","TypeZAS","MnZAS"],"syndicats-eau":["NOM","NOM_SI","SIREN_SI","INSEE_COM"],"syndicats-assain":["NOM","DONNEES__1","DONNEES_SI","INSEE_COM"],"syndicats-riviere":["NOM","NB_Syndic","Syndic_RIV","SI_RIV","SI_RIV_2","SI_RIV_3","INSEE_COM","SIREN_EPCI"],police:["NOM","POLICE_EAU","NOM_2","ID_COURSDE"],"hydro-live":["code_station","libelle_cours_eau","libelle_commune","en_service","date_ouverture_station","date_fermeture_station","qualification_donnees_station"],"river-live":["code_station","nom_cours_eau","libelle_commune","nom_masse_deau","localisation_precise","date_creation","date_arret"],"groundwater-bodies":["code","nom","horizon","milieu","karstique","multicouches","nature_ecoulement"],piezometers:["code_bss","nom_commune","noms_masse_eau_edl","date_debut_mesure","date_fin_mesure","nb_mesures_piezo","altitude_station","profondeur_investigation"],groundwater:["bss_id","code_bss","nom_commune","nom_nature_pe","nom_etat_pe","date_debut_mesure","date_fin_mesure","profondeur_investigation","noms_masse_eau_edl"],etiage:["code_station","libelle_cours_eau","libelle_commune","etat_station"]};
  return (preferred[source.id]||Object.keys(p).slice(0,8)).filter(k=>p[k]!==null&&p[k]!=="").map(k=>[k,p[k]]);
}
function openFeature(source,feature,clickedLatLng){
  const detailToken=++state.detailToken;
  const p=feature.properties||{}; const title=displayTitle(source,p);
  const cards=relevantProps(source,p).map(([k,v])=>`<div class="property"><small>${niceKey(k)}</small><strong>${k==="etateco"?(qualityLabels[String(v)]||v):safe(v)}${k==="TARIF_AEP"?" €/m³":""}</strong></div>`).join("");
  const guide=themeGuide[source.id];document.getElementById("detailContent").innerHTML=`<span class="detail-tag">${source.group} · ${source.producer||"DDT 95"}</span><h2>${safe(title)}</h2><p class="subtitle">${source.title} · ${source.date}</p>${guide?`<section class="theme-explainer"><strong>Ce que montre cette donnée</strong><p>${guide.what}</p><small>${guide.read}</small></section>`:""}<div id="liveDetail"></div><div class="property-grid">${cards}</div><a class="source-link" target="_blank" rel="noopener" href="${externalSourceUrl(source)}">Consulter la source officielle ↗</a>`;
  document.getElementById("detailPanel").classList.add("open");
  if(source.id==="hydro-live"&&p.code_station)loadLatestHydro(p.code_station,p);
  if(source.id==="etiage"&&p.code_station)loadLatestEtiage(p.code_station);
  if(source.id==="fish"&&p.code_station)loadFishData(p.code_station);
  if(source.id==="hydrobio"&&p.code_station_hydrobio)loadHydrobioData(p.code_station_hydrobio);
  if(source.id==="river-live"&&p.code_station)loadRiverQualityData(p.code_station);
  if(source.id==="groundwater"&&p.bss_id)loadGroundwaterData(p.bss_id);
  if(source.id==="piezometers"&&p.code_bss)loadPiezometerData(p.code_bss);
  if(source.id==="secheresse")loadDroughtDetail(p);
  if(source.id==="cours"||source.id==="qualite")loadRiverProfile(title,feature,clickedLatLng,detailToken);
}
function loadDroughtDetail(p){
  const box=document.getElementById("liveDetail");const basin=String(p.LbZAS||p.MnZAS||"");
  const situation=basin.includes("Vexin")?{level:"Alerte",tone:"warning",detail:"Le bassin du Vexin est placé en alerte sécheresse."}:basin.includes("Oise")?{level:"Alerte renforcée",tone:"danger",detail:"Le bassin Oise et Seine est placé en alerte renforcée."}:{level:"Restrictions en vigueur",tone:"warning",detail:"Des mesures temporaires de limitation s’appliquent sur le département ; l’arrêté précise les communes et usages concernés."};
  box.innerHTML=`<section class="drought-current"><div class="drought-heading"><span>SITUATION EN VIGUEUR · 21 JUILLET 2026</span><strong>${situation.level}</strong><small>${situation.detail}</small></div><div class="drought-order"><strong>Arrêté préfectoral n°2026-18867</strong><span>Signé le 17 juillet 2026 · limitations ou interdictions provisoires des usages de l’eau.</span></div><h3>Principales règles pour les particuliers</h3><ul><li>Pelouses, massifs et espaces verts : arrosage interdit.</li><li>Jardins potagers : arrosage interdit entre 9 h et 20 h.</li><li>Voies, trottoirs, terrasses et façades : lavage interdit.</li><li>Véhicules : lavage à domicile interdit ; stations économes ou haute pression uniquement.</li><li>Piscines privées de plus de 1 m³ : remplissage et vidange interdits, sauf exceptions prévues par l’arrêté.</li></ul><p class="drought-note">Le niveau peut évoluer par nouvel arrêté. La zone colorée montre le bassin de gestion ; elle ne remplace pas la lecture des mesures applicables à la commune et à l’usage concerné.</p><a class="drought-link" target="_blank" rel="noopener" href="https://www.val-doise.gouv.fr/Actualites/Vigilance-canicule-et-secheresse">Lire l’arrêté et la situation officielle ↗</a></section>`;
}
async function loadLatestHydro(code,p){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Recherche des dernières mesures disponibles…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v2/hydrometrie/observations_tr?code_entite=${encodeURIComponent(code)}&grandeur_hydro=H&size=1&fields=code_station,date_obs,resultat_obs,grandeur_hydro`;const r=await fetch(u);if(!r.ok)throw new Error(`Hub’Eau ${r.status}`);const d=await r.json();const o=d.data?.[0];if(!o)throw new Error("Pas de mesure Hub’Eau");box.innerHTML=`<div class="property live-property"><small>DERNIÈRE HAUTEUR DISPONIBLE</small><strong>${(Number(o.resultat_obs)/1000).toLocaleString("fr-FR",{maximumFractionDigits:3})} m</strong><span>${new Date(o.date_obs).toLocaleString("fr-FR")} · mesure brute Hub’Eau</span></div>`}catch(e){const hasHeight=p.snapshot_hauteur_m!==null&&p.snapshot_hauteur_m!==undefined&&Number.isFinite(Number(p.snapshot_hauteur_m)),hasFlow=p.snapshot_debit_m3s!==null&&p.snapshot_debit_m3s!==undefined&&Number.isFinite(Number(p.snapshot_debit_m3s));box.innerHTML=hasHeight||hasFlow?`<div class="snapshot-notice">Dernier relevé sécurisé depuis Vigicrues · le direct Hub’Eau est indisponible.</div><div class="hydro-live-grid">${hasHeight?`<div class="property live-property"><small>HAUTEUR</small><strong>${Number(p.snapshot_hauteur_m).toLocaleString("fr-FR",{maximumFractionDigits:3})} m</strong><span>${new Date(p.snapshot_date_hauteur).toLocaleString("fr-FR")} · Vigicrues</span></div>`:""}${hasFlow?`<div class="property live-property"><small>DÉBIT</small><strong>${Number(p.snapshot_debit_m3s).toLocaleString("fr-FR",{maximumFractionDigits:3})} m³/s</strong><span>${new Date(p.snapshot_date_debit).toLocaleString("fr-FR")} · Vigicrues</span></div>`:""}</div>`:'<p class="subtitle">Cette station appartient au référentiel national, mais aucune mesure récente n’est publiée par Vigicrues.</p>'}}
async function loadLatestEtiage(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des observations visuelles OFB…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/ecoulement/observations?code_station=${encodeURIComponent(code)}&size=12`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const rows=(d.data||[]).sort((a,b)=>new Date(b.date_observation)-new Date(a.date_observation));const latest=rows[0];if(!latest){box.innerHTML='<p class="subtitle">Aucune observation publiée pour cette station.</p>';return}const codeEtat=String(latest.code_ecoulement||"");const level=codeEtat.startsWith("1")?"good":codeEtat.startsWith("2")?"warning":codeEtat.startsWith("3")?"danger":"unknown";const meaning=codeEtat.startsWith("1")?"L’eau circule encore dans le lit du cours d’eau.":codeEtat.startsWith("2")?"L’écoulement est interrompu par endroits : le cours d’eau devient vulnérable.":codeEtat.startsWith("3")?"Le lit est à sec sur la station : la situation est critique pour les milieux aquatiques.":"Observation visuelle réalisée par l’Office français de la biodiversité.";box.innerHTML=`<section class="flow-explainer"><span>À QUOI ÇA SERT ?</span><p>Le réseau Onde suit visuellement les petits cours d’eau pendant les périodes sèches. Il permet de repérer une baisse anormale de l’écoulement avant ou pendant une sécheresse.</p></section><section class="flow-status ${level}"><small>DERNIÈRE OBSERVATION · ${new Date(latest.date_observation).toLocaleDateString("fr-FR")}</small><strong>${htmlSafe(latest.libelle_ecoulement)}</strong><p>${meaning}</p></section><div class="flow-history"><strong>Historique récent</strong>${rows.slice(0,6).map(o=>`<div><time>${new Date(o.date_observation).toLocaleDateString("fr-FR")}</time><span>${htmlSafe(o.libelle_ecoulement)}</span></div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les observations Onde sont momentanément indisponibles.</p>'}}
async function loadFishData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des espèces et effectifs observés…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/etat_piscicole/observations?code_station=${encodeURIComponent(code)}&size=20000`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const all=d.data||[];if(!all.length){box.innerHTML='<p class="subtitle">Aucune observation piscicole publiée pour cette station.</p>';return}all.sort((a,b)=>new Date(b.date_operation)-new Date(a.date_operation));const lastDate=all[0].date_operation;const rows=all.filter(x=>x.date_operation===lastDate);const species={};rows.forEach(x=>{const n=x.nom_commun_taxon||x.nom_latin_taxon||"Taxon non renseigné";const a=species[n]??={effectif:0,min:null,max:null,latin:x.nom_latin_taxon};a.effectif+=Number(x.effectif_lot||1);if(Number.isFinite(Number(x.taille_min_lot)))a.min=a.min===null?Number(x.taille_min_lot):Math.min(a.min,Number(x.taille_min_lot));if(Number.isFinite(Number(x.taille_max_lot)))a.max=a.max===null?Number(x.taille_max_lot):Math.max(a.max,Number(x.taille_max_lot))});const list=Object.entries(species).sort((a,b)=>b[1].effectif-a[1].effectif);box.innerHTML=`<section class="data-summary"><strong>Dernière pêche scientifique · ${new Date(lastDate).toLocaleDateString("fr-FR")}</strong><span>${list.length} espèce(s) · ${list.reduce((n,[,x])=>n+x.effectif,0).toLocaleString("fr-FR")} individu(s) ou effectifs de lots publiés</span><small>${htmlSafe(rows[0].protocole_peche||"Protocole non renseigné")}</small></section><div class="analysis-list">${list.map(([name,x])=>`<div class="analysis-row"><span><b>${htmlSafe(name)}</b>${x.latin&&x.latin!==name?`<small>${htmlSafe(x.latin)}</small>`:""}</span><strong>${x.effectif.toLocaleString("fr-FR")}</strong>${x.min!==null||x.max!==null?`<small>Taille observée : ${x.min??"—"} à ${x.max??"—"} mm</small>`:""}</div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les observations piscicoles sont momentanément indisponibles.</p>'}}
async function loadHydrobioData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des indices biologiques mesurés…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/hydrobio/indices?code_station_hydrobio=${encodeURIComponent(code)}&size=5000`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const all=d.data||[];if(!all.length){box.innerHTML='<p class="subtitle">Aucun indice biologique publié pour cette station.</p>';return}all.sort((a,b)=>new Date(b.date_prelevement)-new Date(a.date_prelevement));const lastDate=all[0].date_prelevement;const rows=all.filter(x=>x.date_prelevement===lastDate);const supports=[...new Set(rows.map(x=>x.libelle_support).filter(Boolean))];box.innerHTML=`<section class="data-summary"><strong>Dernier prélèvement biologique · ${new Date(lastDate).toLocaleDateString("fr-FR")}</strong><span>${rows.length} indice(s) · ${htmlSafe(supports.join(", ")||"support non renseigné")}</span><small>Ces indices décrivent la diversité, l’abondance et la sensibilité des organismes à la dégradation du milieu.</small></section><div class="analysis-list">${rows.map(x=>`<div class="analysis-row"><span>${htmlSafe(x.libelle_indice)}</span><strong>${Number(x.resultat_indice).toLocaleString("fr-FR")} ${htmlSafe(x.unite_indice||"")}</strong><small>${htmlSafe(x.libelle_support||"")} · donnée ${htmlSafe(x.libelle_qualification||"non qualifiée")}</small></div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les indices hydrobiologiques sont momentanément indisponibles.</p>'}}
async function loadRiverQualityData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des dernières analyses de la rivière…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_station=${encodeURIComponent(code)}&date_debut_prelevement=${monthsAgo(18)}&size=5000`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const all=d.data||[];if(!all.length){box.innerHTML='<p class="subtitle">Aucune analyse publiée sur les 18 derniers mois.</p>';return}all.sort((a,b)=>new Date(b.date_prelevement)-new Date(a.date_prelevement));const lastDate=all[0].date_prelevement;const rows=all.filter(x=>x.date_prelevement===lastDate);box.innerHTML=`<section class="data-summary"><strong>Dernier prélèvement · ${new Date(lastDate).toLocaleDateString("fr-FR")}</strong><span>${rows.length} paramètre(s) analysé(s)</span><small>Eau, sédiments ou autre support : le support est précisé pour chaque résultat.</small></section><div class="analysis-list">${rows.map(x=>`<div class="analysis-row"><span>${htmlSafe(x.libelle_parametre)}</span><strong>${Number(x.resultat).toLocaleString("fr-FR")} ${htmlSafe(x.symbole_unite||"")}</strong><small>${htmlSafe(x.libelle_support||"")} · ${htmlSafe(x.mnemo_remarque||x.libelle_qualification||"")}</small></div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les analyses de la rivière sont momentanément indisponibles.</p>'}}
async function loadGroundwaterData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des analyses de la nappe…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/qualite_nappes/analyses?bss_id=${encodeURIComponent(code)}&size=5000`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const all=d.data||[];if(!all.length){box.innerHTML='<p class="subtitle">Aucune analyse publiée pour ce point.</p>';return}all.sort((a,b)=>new Date(b.date_debut_prelevement)-new Date(a.date_debut_prelevement));const lastDate=all[0].date_debut_prelevement;const rows=all.filter(x=>x.date_debut_prelevement===lastDate);box.innerHTML=`<section class="data-summary"><strong>Dernier prélèvement · ${new Date(lastDate).toLocaleDateString("fr-FR")}</strong><span>${rows.length} paramètre(s) analysé(s)</span><small>Les mentions « inférieur au seuil » signifient que la substance n’a pas été quantifiée au-dessus de la capacité de mesure du laboratoire.</small></section><div class="analysis-list">${rows.map(x=>`<div class="analysis-row"><span>${htmlSafe(x.nom_param)}</span><strong>${Number(x.resultat).toLocaleString("fr-FR")} ${htmlSafe(x.symbole_unite||"")}</strong><small>${htmlSafe(x.nom_remarque_analyse||x.nom_qualification||"")}</small></div>`).join("")}</div>`}catch(e){box.innerHTML='<p class="subtitle">Les analyses de la nappe sont momentanément indisponibles.</p>'}}
async function loadPiezometerData(code){const box=document.getElementById("liveDetail");box.innerHTML='<p class="subtitle">Chargement des derniers niveaux de la nappe…</p>';try{const u=`https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=${encodeURIComponent(code)}&size=24&sort=desc`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();const rows=d.data||[];if(!rows.length){box.innerHTML='<p class="subtitle">Aucune mesure piézométrique publiée pour cette station.</p>';return}const latest=rows[0],oldest=rows[rows.length-1];const delta=Number(latest.niveau_nappe_eau)-Number(oldest.niveau_nappe_eau);const trend=Math.abs(delta)<.02?"stable":delta>0?"en hausse":"en baisse";const trendClass=Math.abs(delta)<.02?"stable":delta>0?"up":"down";box.innerHTML=`<section class="piezo-summary"><span>DERNIÈRE MESURE · ${new Date(latest.date_mesure).toLocaleDateString("fr-FR")}</span><div class="piezo-main"><strong>${Number(latest.niveau_nappe_eau).toLocaleString("fr-FR",{maximumFractionDigits:2})} m NGF</strong><b class="${trendClass}">${trend} ${Math.abs(delta).toLocaleString("fr-FR",{maximumFractionDigits:2})} m</b></div><small>Cote altimétrique de l’eau par rapport au nivellement général de la France. Évolution calculée sur les ${rows.length} dernières mesures publiées.</small></section><div class="piezo-metrics"><div><small>PROFONDEUR PUBLIÉE</small><strong>${Number(latest.profondeur_nappe).toLocaleString("fr-FR",{maximumFractionDigits:2})} m</strong></div><div><small>QUALIFICATION</small><strong>${htmlSafe(latest.qualification||"Non renseignée")}</strong></div></div><div class="piezo-history"><strong>Dernières mesures</strong>${rows.slice(0,8).map(x=>`<div><time>${new Date(x.date_mesure).toLocaleDateString("fr-FR")}</time><span>${Number(x.niveau_nappe_eau).toLocaleString("fr-FR",{maximumFractionDigits:2})} m NGF</span><small>${Number(x.profondeur_nappe).toLocaleString("fr-FR",{maximumFractionDigits:2})} m</small></div>`).join("")}</div><p class="piezo-note">Une cote plus élevée traduit une nappe plus haute à cette station. Pour qualifier la situation de « haute », « normale » ou « basse », il faut comparer cette valeur aux statistiques historiques propres au piézomètre.</p>`}catch(e){box.innerHTML='<p class="subtitle">Les niveaux de nappe sont momentanément indisponibles via Hub’Eau.</p>'}}
function normRiver(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\b(le|la|les|l|ru|rivière|riviere|cours|eau)\b/g," ").replace(/[^a-z0-9]+/g," ").trim()}
function pointOf(feature){const g=feature?.geometry;if(!g)return null;let c=g.coordinates;while(Array.isArray(c?.[0]))c=c[Math.floor(c.length/2)];return Array.isArray(c)&&Number.isFinite(c[0])&&Number.isFinite(c[1])?{lng:c[0],lat:c[1]}:null}
function distanceKm(a,b){const rad=Math.PI/180,dLat=(b.lat-a.lat)*rad,dLon=(b.lng-a.lng)*rad,x=Math.sin(dLat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function bestStation(features,latlng,riverName,fields){const target=normRiver(riverName);let ranked=(features||[]).map(f=>{const p=f.properties||f;const pt=pointOf(f)||((Number.isFinite(p.longitude)&&Number.isFinite(p.latitude))?{lng:p.longitude,lat:p.latitude}:null);if(!pt)return null;const names=fields.map(k=>normRiver(p[k])).filter(Boolean);const exact=target&&names.some(n=>n===target||n.includes(target)||target.includes(n));return {feature:f,km:distanceKm(latlng,pt),exact}}).filter(Boolean);ranked.sort((a,b)=>(b.exact-a.exact)||(a.km-b.km));return ranked[0]||null}
function riverMetric(label,value,unit,note){return `<div class="river-metric"><small>${label}</small><strong>${value??"—"}${value!==null&&value!==undefined&&unit?` ${unit}`:""}</strong>${note?`<span>${note}</span>`:""}</div>`}
async function loadRiverProfile(riverName,feature,clickedLatLng,token){const box=document.getElementById("liveDetail");if(!box)return;const fallback=pointOf(feature);const here=clickedLatLng||fallback;if(!here)return;box.innerHTML='<section class="river-loading">Construction du portrait de la rivière à partir des réseaux DDT 95, Naïades, Vigicrues et Onde…</section>';try{
  await Promise.all(["river-live","hydro-live","etiage"].map(id=>loadSource(sources.find(s=>s.id===id))));if(token!==state.detailToken)return;
  const qualityMatch=bestStation(state.data["river-live"]?.features,here,riverName,["nom_cours_eau","libelle_station"]);const hydroMatch=bestStation(state.data["hydro-live"]?.features,here,riverName,["libelle_cours_eau","libelle_station"]);const ondeMatch=bestStation(state.data.etiage?.features,here,riverName,["libelle_cours_eau","libelle_station"]);
  const ecoFeatures=state.data.qualite?.features||[];const eco=ecoFeatures.find(f=>{const n=normRiver(f.properties?.name);const t=normRiver(riverName);return n&&t&&(n===t||n.includes(t)||t.includes(n))});
  const qp=qualityMatch?.feature.properties;const hp=hydroMatch?.feature.properties;const op=ondeMatch?.feature.properties;
  const requests=[];
  requests.push(qp&&(qualityMatch.exact||qualityMatch.km<8)?fetch(`https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_station=${encodeURIComponent(qp.code_station)}&date_debut_prelevement=${monthsAgo(18)}&size=5000`).then(r=>r.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}));
  requests.push(hp&&(hydroMatch.exact||hydroMatch.km<10)?fetch(`https://hubeau.eaufrance.fr/api/v2/hydrometrie/observations_tr?code_entite=${encodeURIComponent(hp.code_station)}&grandeur_hydro=H&size=1`).then(r=>r.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}));
  requests.push(hp&&(hydroMatch.exact||hydroMatch.km<10)?fetch(`https://hubeau.eaufrance.fr/api/v2/hydrometrie/observations_tr?code_entite=${encodeURIComponent(hp.code_station)}&grandeur_hydro=Q&size=1`).then(r=>r.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}));
  requests.push(op&&(ondeMatch.exact||ondeMatch.km<8)?fetch(`https://hubeau.eaufrance.fr/api/v1/ecoulement/observations?code_station=${encodeURIComponent(op.code_station)}&size=1`).then(r=>r.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}));
  const [qualityJson,heightJson,flowJson,ondeJson]=await Promise.all(requests);if(token!==state.detailToken)return;
  const analyses=(qualityJson.data||[]).sort((a,b)=>new Date(b.date_prelevement)-new Date(a.date_prelevement));const lastQualityDate=analyses[0]?.date_prelevement;const latestAnalyses=lastQualityDate?analyses.filter(x=>x.date_prelevement===lastQualityDate):[];const snapshotH=hp?.snapshot_hauteur_m!==null&&hp?.snapshot_hauteur_m!==undefined?{resultat_obs:Number(hp.snapshot_hauteur_m)*1000,date_obs:hp.snapshot_date_hauteur}:null,snapshotQ=hp?.snapshot_debit_m3s!==null&&hp?.snapshot_debit_m3s!==undefined?{resultat_obs:Number(hp.snapshot_debit_m3s)*1000,date_obs:hp.snapshot_date_debit}:null;const h=heightJson.data?.[0]||snapshotH,q=flowJson.data?.[0]||snapshotQ,onde=ondeJson.data?.[0];const ecoCode=String(eco?.properties?.etateco||"U");
  const qualityRows=latestAnalyses.slice(0,20).map(x=>`<div class="analysis-row"><span>${htmlSafe(x.libelle_parametre)}</span><strong>${Number(x.resultat).toLocaleString("fr-FR")} ${htmlSafe(x.symbole_unite||"")}</strong><small>${htmlSafe(x.libelle_support||"")} · ${htmlSafe(x.mnemo_remarque||x.libelle_qualification||"")}</small></div>`).join("");
  box.innerHTML=`<section class="river-profile"><div class="river-profile-head"><span>PORTRAIT MULTISOURCE</span><strong>${htmlSafe(riverName)}</strong><small>Données rapprochées du point cliqué ; la distance à chaque station est indiquée.</small></div><div class="river-metrics">${riverMetric("État écologique",qualityLabels[ecoCode]||"Non classé","",eco?.properties?.annee?`Millésime ${eco.properties.annee}`:"Couche DDT 95")}${riverMetric("Hauteur récente",h?(Number(h.resultat_obs)/1000).toLocaleString("fr-FR",{maximumFractionDigits:3}):null,"m",h?`${new Date(h.date_obs).toLocaleString("fr-FR")} · station à ${hydroMatch.km.toFixed(1)} km`:"Pas de station hydrométrique pertinente")}${riverMetric("Débit récent",q?(Number(q.resultat_obs)/1000).toLocaleString("fr-FR",{maximumFractionDigits:3}):null,"m³/s",q?`${new Date(q.date_obs).toLocaleString("fr-FR")} · mesure brute Vigicrues`:"Débit non disponible")}${riverMetric("Étiage Onde",onde?htmlSafe(onde.libelle_ecoulement):null,"",onde?`${new Date(onde.date_observation).toLocaleDateString("fr-FR")} · station à ${ondeMatch.km.toFixed(1)} km`:"Pas d’observation Onde pertinente")}</div>${qp?`<section class="river-source-line"><strong>Station qualité retenue</strong><span>${htmlSafe(qp.libelle_station||qp.nom_cours_eau)} · ${qualityMatch.km.toFixed(1)} km du clic</span></section>`:""}${latestAnalyses.length?`<section class="data-summary"><strong>Dernier prélèvement de qualité · ${new Date(lastQualityDate).toLocaleDateString("fr-FR")}</strong><span>${latestAnalyses.length} paramètre(s) publié(s) pour cette campagne</span><small>Les résultats ci-dessous sont des mesures de laboratoire ; ils ne constituent pas seuls le classement écologique global.</small></section><div class="analysis-list">${qualityRows}${latestAnalyses.length>20?`<div class="analysis-more">+ ${latestAnalyses.length-20} autres paramètres dans la source Hub’Eau</div>`:""}</div>`:'<p class="subtitle">Aucune analyse récente trouvée sur la station de qualité la plus pertinente.</p>'}</section>`;
}catch(e){if(token===state.detailToken)box.innerHTML='<p class="subtitle">Le portrait multisource de cette rivière est momentanément indisponible.</p>'}}
const potableColors={conforme:"#16a34a",vigilance:"#f59e0b",nonconforme:"#dc2626",nodata:"#94a3b8"};
function swatchBackground(source){
  if(source.kind==="quality")return `linear-gradient(90deg,${qualityColors["2"]} 0 25%,${qualityColors["3"]} 25% 50%,${qualityColors["4"]} 50% 75%,${qualityColors["5"]} 75%)`;
  if(source.kind==="groundwater-body")return `linear-gradient(90deg,${Object.values(groundwaterColors).map((c,i,a)=>`${c} ${i*100/a.length}% ${(i+1)*100/a.length}%`).join(",")})`;
  if(source.kind==="price")return "linear-gradient(90deg,#d9d4f5 0 25%,#9b8cdc 25% 50%,#6554c0 50% 75%,#3f2c80 75%)";
  if(source.kind==="api-commune")return `linear-gradient(90deg,${potableColors.conforme} 0 33%,${potableColors.vigilance} 33% 66%,${potableColors.nonconforme} 66%)`;
  if(["police","syndicats-eau","syndicats-assain","syndicats-riviere","secheresse"].includes(source.id))return `linear-gradient(90deg,${categoryPalette.slice(0,6).map((c,i)=>`${c} ${i*100/6}% ${(i+1)*100/6}%`).join(",")})`;
  return source.color;
}
function potableStatus(rows){if(!rows.length)return "nodata";if(rows.some(r=>r.conformite_limites_bact_prelevement!=="C"||r.conformite_limites_pc_prelevement!=="C"))return "nonconforme";if(rows.some(r=>r.conformite_references_bact_prelevement!=="C"||r.conformite_references_pc_prelevement!=="C"))return "vigilance";return "conforme"}
async function loadPotableSource(source){
  if(!state.communes)await loadCommunes();
  const fields="code_commune,nom_commune,code_prelevement,date_prelevement,conclusion_conformite_prelevement,conformite_limites_bact_prelevement,conformite_limites_pc_prelevement,conformite_references_bact_prelevement,conformite_references_pc_prelevement,nom_distributeur,nom_moa";
  const url=`${source.api}?code_departement=95&code_parametre=1340&date_min_prelevement=${monthsAgo(12)}&size=5000&fields=${encodeURIComponent(fields)}`;
  const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(`Hub’Eau ${r.status}`);const d=await r.json();
  const byCommune={};const seen=new Set();(d.data||[]).forEach(x=>{if(!x.code_commune||seen.has(x.code_prelevement))return;seen.add(x.code_prelevement);(byCommune[x.code_commune]??=[]).push(x)});
  state.potableAgg={};Object.entries(byCommune).forEach(([code,rows])=>{rows.sort((a,b)=>new Date(b.date_prelevement)-new Date(a.date_prelevement));const lim=rows.filter(x=>x.conformite_limites_bact_prelevement==="C"&&x.conformite_limites_pc_prelevement==="C").length;const ref=rows.filter(x=>x.conformite_references_bact_prelevement==="C"&&x.conformite_references_pc_prelevement==="C").length;const incidents=rows.filter(x=>x.conformite_limites_bact_prelevement!=="C"||x.conformite_limites_pc_prelevement!=="C"||x.conformite_references_bact_prelevement!=="C"||x.conformite_references_pc_prelevement!=="C");state.potableAgg[code]={rows,incidents,nb:rows.length,status:potableStatus(rows),tauxLimites:Math.round(lim/rows.length*1000)/10,tauxReferences:Math.round(ref/rows.length*1000)/10,dernier:rows[0]}});
  state.data[source.id]={type:"FeatureCollection",features:state.communes.features.map(f=>({type:"Feature",geometry:f.geometry,properties:{...f.properties,...(state.potableAgg[f.properties.code]||{status:"nodata",nb:0})}}))};
  state.layers[source.id]=L.geoJSON(state.data[source.id],{style:f=>({color:"#fff",weight:1,fillColor:potableColors[f.properties.status],fillOpacity:.68}),onEachFeature:(f,l)=>{l.bindTooltip(`${f.properties.nom} · ${f.properties.nb||0} prélèvement(s)`,{sticky:true});l.on("click",()=>openPotableDetail(f.properties.code,f.properties.nom,source))}});return state.layers[source.id]
}
async function openPotableDetail(code,nom,source){
  const agg=state.potableAgg?.[code]||{status:"nodata",nb:0};const labels={conforme:"Conforme",vigilance:"Dépassement d’une référence de qualité",nonconforme:"Non-conformité détectée",nodata:"Pas de prélèvement récent"};
  document.getElementById("detailContent").innerHTML=`<span class="detail-tag">QUALITÉ SANITAIRE · HUB’EAU / ARS</span><h2>${htmlSafe(nom)}</h2><div class="water-status ${agg.status}">${labels[agg.status]}</div>${agg.incidents?.length?`<p class="status-period">Au moins un contrôle non conforme sur les douze derniers mois · le dernier contrôle peut être conforme.</p>`:""}<div class="property-grid"><div class="property"><small>PRÉLÈVEMENTS · 12 MOIS</small><strong>${agg.nb}</strong></div><div class="property"><small>CONFORMITÉ LIMITES</small><strong>${agg.tauxLimites??"—"} %</strong></div><div class="property"><small>CONFORMITÉ RÉFÉRENCES</small><strong>${agg.tauxReferences??"—"} %</strong></div><div class="property"><small>DERNIER CONTRÔLE</small><strong>${agg.dernier?.date_prelevement?new Date(agg.dernier.date_prelevement).toLocaleDateString("fr-FR"):"—"}</strong></div></div><div id="liveDetail"><p class="subtitle">Recherche des paramètres à l’origine du classement…</p></div><a class="source-link" target="_blank" rel="noopener" href="${externalSourceUrl(source)}">Consulter l’API officielle ↗</a>`;document.getElementById("detailPanel").classList.add("open");
  if(!agg.dernier)return document.getElementById("liveDetail").innerHTML='<p class="subtitle">Aucune analyse récente publiée pour cette commune.</p>';
  try{const fields="code_prelevement,date_prelevement,libelle_parametre,resultat_alphanumerique,resultat_numerique,libelle_unite,limite_qualite_parametre,reference_qualite_parametre,conclusion_conformite_prelevement,nom_distributeur,nom_moa";const controls=agg.incidents?.length?agg.incidents:[agg.dernier];const payloads=await Promise.all(controls.map(async control=>{const u=`${source.api}?code_prelevement=${encodeURIComponent(control.code_prelevement)}&size=5000&fields=${encodeURIComponent(fields)}`;const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();return {control,rows:d.data||[]}}));const incidentCards=payloads.map(({control,rows})=>{const conclusion=control.conclusion_conformite_prelevement||rows[0]?.conclusion_conformite_prelevement||"Conclusion non renseignée";const exceeded=rows.filter(x=>parameterExceeded(x,conclusion));return `<section class="water-incident"><div class="water-incident-head"><span>CONTRÔLE DU ${new Date(control.date_prelevement).toLocaleDateString("fr-FR")}</span><strong>${exceeded.length?`${exceeded.length} paramètre(s) identifié(s)`:"Non-conformité signalée par l’ARS"}</strong></div>${exceeded.length?`<div class="exceedance-list">${exceeded.map(x=>`<div class="exceedance"><span>${htmlSafe(x.libelle_parametre)}</span><strong>${htmlSafe(x.resultat_alphanumerique)} ${htmlSafe(x.libelle_unite||"")}</strong><small>${x.limite_qualite_parametre?"Limite de qualité": "Référence de qualité"} : ${htmlSafe(x.limite_qualite_parametre||x.reference_qualite_parametre||"non publiée")}</small></div>`).join("")}</div>`:""}<details><summary>Conclusion complète de l’ARS</summary><p>${htmlSafe(conclusion)}</p></details></section>`}).join("");const latest=agg.dernier;document.getElementById("liveDetail").innerHTML=`${agg.incidents?.length?`<h3 class="detail-section-title">Ce qui n’est pas conforme</h3>${incidentCards}`:`<section class="analysis-summary"><strong>${htmlSafe(latest.conclusion_conformite_prelevement||"Contrôle conforme")}</strong><span>Dernier contrôle du ${new Date(latest.date_prelevement).toLocaleDateString("fr-FR")}</span></section>`}<p class="water-reading-note">Une non-conformité réglementaire ne signifie pas automatiquement que l’eau est impropre à la consommation. La conclusion de l’ARS précise les éventuelles restrictions et le niveau de risque sanitaire.</p>`}catch(e){document.getElementById("liveDetail").innerHTML='<p class="subtitle">Le détail des analyses est momentanément indisponible.</p>'}
}
function parameterExceeded(row,conclusion=""){
  const label=String(row.libelle_parametre||"").toLocaleLowerCase("fr").normalize("NFD").replace(/[\u0300-\u036f]/g,"");const note=String(conclusion).toLocaleLowerCase("fr").normalize("NFD").replace(/[\u0300-\u036f]/g,"");
  const censored=String(row.resultat_alphanumerique||"").trim().startsWith("<");if(label.length>5&&note.includes(label)&&!censored)return true;
  const threshold=String(row.limite_qualite_parametre||row.reference_qualite_parametre||"").replace(",",".");const result=Number(row.resultat_numerique);if(!Number.isFinite(result)||censored)return false;
  const max=threshold.match(/<=?\s*([0-9.]+)/),min=threshold.match(/>=?\s*([0-9.]+)/);return Boolean(max&&result>Number(max[1])||min&&result<Number(min[1]));
}
async function loadSource(source){
  if(!source.file&&!source.api)return null;
  if(source.kind==="api-commune"&&!state.layers[source.id])return loadPotableSource(source);
  if(!state.data[source.id]){const local=source.snapshot||source.file;const r=await fetch(local?DATA_ROOT+local:source.api);if(!r.ok)throw new Error(`${source.title}: ${r.status}`);const d=await r.json();state.data[source.id]=local?d:{type:"FeatureCollection",features:(d.data||[]).filter(x=>x.geometry?.coordinates||Number.isFinite(x.longitude)&&Number.isFinite(x.latitude)).map(x=>({type:"Feature",properties:x,geometry:x.geometry?.coordinates?x.geometry:{type:"Point",coordinates:[x.longitude,x.latitude]}}))}}
  if(!state.layers[source.id]){
    const data=source.kind==="groundwater-body"?{type:"FeatureCollection",features:state.data[source.id].features.filter(f=>Number(f.properties.horizon)===state.groundwaterHorizon)}:state.data[source.id];state.layers[source.id]=makeGeoLayer(source,data);
  }
  return state.layers[source.id];
}
function makeGeoLayer(source,data){return L.geoJSON(data,{style:f=>layerStyle(source,f),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:7,color:"#fff",weight:2,fillColor:source.color,fillOpacity:1}),onEachFeature:(f,l)=>{l.on("click",e=>openFeature(source,f,e.latlng));l.bindTooltip(displayTitle(source,f.properties||{}),{sticky:true})}})}
async function setGroundwaterHorizon(horizon){state.groundwaterHorizon=Number(horizon);document.querySelectorAll("[data-horizon]").forEach(b=>{const active=Number(b.dataset.horizon)===state.groundwaterHorizon;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))});const source=sources.find(s=>s.id==="groundwater-bodies"),control=document.getElementById("layer-groundwater-bodies");if(!state.data[source.id])await loadSource(source);const wasVisible=state.layers[source.id]&&map.hasLayer(state.layers[source.id]);if(state.layers[source.id])map.removeLayer(state.layers[source.id]);const data={type:"FeatureCollection",features:(state.data[source.id]?.features||[]).filter(f=>Number(f.properties.horizon)===state.groundwaterHorizon)};state.layers[source.id]=makeGeoLayer(source,data);if(wasVisible)state.layers[source.id].addTo(map);if(control?.checked)renderLegend(source);document.getElementById("mapStatus").textContent=`Masses d’eau souterraines · horizon ${state.groundwaterHorizon} affiché · ${data.features.length} emprise(s)`}
async function setLayer(source,on){
  const control=document.getElementById(`layer-${source.id}`);
  if(source.kind==="unavailable"){control.checked=false;openFeature(source,{properties:{État:"La source officielle est référencée, mais aucune géométrie directement exploitable n’est actuellement publiée pour cette carte. Elle reste visible pour garantir la traçabilité du thème."}});return}
  control.disabled=true;if(on)document.getElementById("mapStatus").textContent=`Chargement : ${source.title}…`;if(on&&source.kind==="groundwater-body")["cours","qualite","stations"].forEach(id=>{const c=document.getElementById(`layer-${id}`),layer=state.layers[id];if(c?.checked){c.checked=false;if(layer)map.removeLayer(layer)}});
  try{const layer=await loadSource(source);if(on)layer.addTo(map);else map.removeLayer(layer);document.getElementById("mapStatus").textContent=on?`${source.title} affiché · ${source.count}`:"Couche retirée de la carte";if(on)renderLegend(source);else if(state.legendId===source.id)refreshLegend()}catch(e){if(state.layers[source.id])map.removeLayer(state.layers[source.id]);control.checked=false;refreshLegend();document.getElementById("mapStatus").textContent=`Impossible d’afficher cette couche : ${source.title}. Réessayez dans un instant.`;console.error(e)}finally{control.disabled=false}
}
function legendControls(currentId=""){
  const usable=sources.filter(s=>s.kind!=="unavailable"),groups=[...new Set(usable.map(s=>s.group))];
  return `<div class="legend-controls"><label for="legendLayerSelect">Choisir une couche</label><div><select id="legendLayerSelect"><option value="">— Sélectionner —</option>${groups.map(g=>`<optgroup label="${g}">${usable.filter(s=>s.group===g).map(s=>`<option value="${s.id}" ${s.id===currentId?"selected":""}>${s.title}</option>`).join("")}</optgroup>`).join("")}</select><button id="legendLayerHide" type="button" ${currentId?"":"disabled"}>Masquer</button></div></div>`;
}
function bindLegendControls(){
  const select=document.getElementById("legendLayerSelect"),hide=document.getElementById("legendLayerHide");if(!select)return;
  select.onchange=async()=>{const source=sources.find(s=>s.id===select.value);if(!source)return;const control=document.getElementById(`layer-${source.id}`);if(!control.checked){control.checked=true;await setLayer(source,true)}else renderLegend(source)};
  if(hide)hide.onclick=()=>{const source=sources.find(s=>s.id===state.legendId),control=source&&document.getElementById(`layer-${source.id}`);if(source&&control){control.checked=false;setLayer(source,false)}};
  document.querySelectorAll("#mapLegend [data-legend-horizon]").forEach(b=>b.onclick=()=>setGroundwaterHorizon(b.dataset.legendHorizon));
}
function refreshLegend(){const active=[...sources].reverse().find(s=>document.getElementById(`layer-${s.id}`)?.checked&&state.layers[s.id]&&map.hasLayer(state.layers[s.id]));if(active)renderLegend(active);else{state.legendId=null;const el=document.getElementById("mapLegend");el.innerHTML=`${legendControls()}<div class="legend-empty"><strong>Lecture de la carte</strong><span>Sélectionnez une couche pour afficher sa légende.</span></div>`;bindLegendControls()}}
function renderLegend(source){const el=document.getElementById("mapLegend");let rows=[];
  if(source.kind==="quality")rows=Object.entries(qualityLabels).map(([k,v])=>[qualityColors[k],v]);
  else if(source.kind==="groundwater-body"){const features=(state.data[source.id]?.features||[]).filter(f=>Number(f.properties.horizon)===state.groundwaterHorizon),seen=new Set();rows=features.filter(f=>!seen.has(f.properties.code)&&seen.add(f.properties.code)).map(f=>[groundwaterColors[f.properties.code]||source.color,f.properties.nom]);}
  else if(source.kind==="api-commune")rows=[[potableColors.conforme,"Conforme"],[potableColors.vigilance,"Référence dépassée"],[potableColors.nonconforme,"Non conforme"],[potableColors.nodata,"Sans donnée récente"]];
  else if(source.kind==="price")rows=[["#d9d4f5","moins de 2,50 €/m³"],["#9b8cdc","2,50 à 3 €/m³"],["#6554c0","3 à 4 €/m³"],["#3f2c80","4 €/m³ et plus"]];
  else if(["police","secheresse","syndicats-eau","syndicats-assain","syndicats-riviere"].includes(source.id)){const values=[...new Set((state.data[source.id]?.features||[]).map(f=>categoryValue(source,f.properties)).filter(Boolean))];rows=values.slice(0,7).map(v=>[categoryColor(v,source.id),v]);if(values.length>7)rows.push(["#68737d",`+ ${values.length-7} autres catégories`])}
  else rows=[[source.color,source.title]];
  const horizons=source.kind==="groundwater-body"?`<div class="legend-horizons"><b>Profondeur</b>${[1,2,3,4].map(h=>`<button type="button" data-legend-horizon="${h}" class="${h===state.groundwaterHorizon?"active":""}" aria-pressed="${h===state.groundwaterHorizon}">H${h}</button>`).join("")}</div>`:"";
  state.legendId=source.id;el.innerHTML=`${legendControls(source.id)}<div class="legend-content"><strong>${source.title}</strong>${horizons}${rows.map(([c,l])=>`<span><i style="background:${c}"></i>${l}</span>`).join("")}</div>`;bindLegendControls();
}
function renderLayers(){
  const groups=[...new Set(sources.map(s=>s.group))]; const root=document.getElementById("layerList");
  root.innerHTML=groups.map(g=>`<section class="layer-group"><div class="group-title">${g}</div>${sources.filter(s=>s.group===g).map(s=>`<label class="layer-row ${s.kind==="unavailable"?"source-only":""}" style="--layer-color:${s.color}">${s.kind==="unavailable"?`<button id="layer-${s.id}" class="source-control" type="button">Voir</button>`:`<input id="layer-${s.id}" type="checkbox" autocomplete="off" ${s.active?"checked":""}>`}<span class="layer-label"><strong>${s.title}</strong><small>${s.count} · ${s.date}</small><span class="layer-help">${themeGuide[s.id]?.short||"Donnée cartographique"}</span></span><span class="legend-swatch ${s.kind.includes("point")?"point":""}" style="background:${swatchBackground(s)}"></span></label>${s.kind==="groundwater-body"?`<div class="horizon-selector" aria-label="Profondeur de la nappe"><span>Profondeur affichée</span><div>${[1,2,3,4].map(h=>`<button type="button" data-horizon="${h}" aria-pressed="${h===state.groundwaterHorizon}" class="${h===state.groundwaterHorizon?"active":""}">H${h}</button>`).join("")}</div><small>H1 = proche de la surface · H4 = plus profond</small></div>`:""}`).join("")}</section>`).join("");
  root.scrollTop=0;
  sources.forEach(s=>{const control=document.getElementById(`layer-${s.id}`);if(s.kind==="unavailable")control.addEventListener("click",()=>setLayer(s,false));else control.addEventListener("change",e=>setLayer(s,e.target.checked))});document.querySelectorAll("[data-horizon]").forEach(b=>b.addEventListener("click",()=>setGroundwaterHorizon(b.dataset.horizon)));
}
function renderSources(){document.getElementById("sourceCards").innerHTML=sources.map(s=>`<article class="source-card"><div><h3>${s.title}</h3><p>${themeGuide[s.id]?.what||"Donnée territoriale sur l’eau."}<br><b>Lecture :</b> ${themeGuide[s.id]?.read||"Consulter la fiche officielle."}<br>Producteur : ${s.producer||"Direction départementale des territoires du Val-d’Oise"} · ${s.date}</p><span class="source-status">${s.kind==="unavailable"?"Référencée · service indisponible":s.snapshot?"Référentiel local sécurisé · mesures via API":s.api?"Connectée à l’API":"Intégrée à la page"}</span></div><a href="${externalSourceUrl(s)}" target="_blank" rel="noopener">Ouvrir ↗</a></article>`).join("")}
async function loadCommunes(){try{const r=await fetch("https://geo.api.gouv.fr/departements/95/communes?fields=nom,code,centre,contour&format=geojson&geometry=contour");state.communes=await r.json();const holes=[];state.communes.features.forEach(f=>{const g=f.geometry;if(g.type==="Polygon")holes.push(g.coordinates[0]);else if(g.type==="MultiPolygon")g.coordinates.forEach(p=>holes.push(p[0]))});state.mask=L.geoJSON({type:"Feature",properties:{},geometry:{type:"Polygon",coordinates:[[[ -180,-85],[180,-85],[180,85],[-180,85],[-180,-85]],...holes]}},{pane:"maskPane",interactive:false,className:"map-mask",style:{stroke:false,fillColor:"#e7ebf2",fillOpacity:.94,fillRule:"evenodd"}}).addTo(map);state.territory=L.geoJSON(state.communes,{pane:"boundaryPane",interactive:false,style:{color:"#565b6c",weight:.7,opacity:.68,fillOpacity:0}}).addTo(map);map.fitBounds(state.territory.getBounds(),{padding:[10,10]})}catch(e){state.communes={features:[]}}}
async function search(){const q=document.getElementById("searchInput").value.trim();if(!q)return;const box=document.getElementById("searchResults");let items=[];
  if(state.communes)items=state.communes.features.filter(f=>f.properties.nom.toLowerCase().includes(q.toLowerCase())).slice(0,5).map(f=>{const c=L.geoJSON(f).getBounds().getCenter();return {label:f.properties.nom,coords:[c.lat,c.lng]}});
  if(!items.length){try{const r=await fetch(`https://data.geopf.fr/geocodage/search?q=${encodeURIComponent(q+" Val-d'Oise")}&limit=5`);const d=await r.json();items=(d.features||[]).map(f=>({label:f.properties.label,coords:[f.geometry.coordinates[1],f.geometry.coordinates[0]]}))}catch(e){}}
  box.innerHTML=items.length?items.map((x,i)=>`<button data-i="${i}">${x.label}</button>`).join(""):"<button>Aucun résultat dans le Val-d’Oise</button>";box.hidden=false;box.querySelectorAll("button[data-i]").forEach(b=>b.onclick=()=>{const x=items[+b.dataset.i];map.flyTo(x.coords,14);L.popup().setLatLng(x.coords).setContent(`<strong>${x.label}</strong>`).openOn(map);box.hidden=true})
}
function chartData(){
  const q=state.data.qualite?.features||[],keys=Object.keys(qualityLabels),quality=keys.map(k=>q.filter(f=>String(f.properties.etateco)===k).length),qualityKm=keys.map(k=>Math.round(q.filter(f=>String(f.properties.etateco)===k).reduce((a,f)=>a+(Number(f.properties.longueur)||0),0)/1000));
  const priceFeatures=state.data.prix?.features||[],prices=priceFeatures.map(f=>Number(f.properties.TARIF_AEP)).filter(Number.isFinite),bins=[0,0,0,0];prices.forEach(v=>bins[v<2.5?0:v<3?1:v<4?2:3]++);const popTotal=priceFeatures.reduce((a,f)=>a+(Number(f.properties.POPULATION)||0),0),weightedPrice=priceFeatures.reduce((a,f)=>a+(Number(f.properties.TARIF_AEP)||0)*(Number(f.properties.POPULATION)||0),0)/(popTotal||1);
  const counts=id=>(state.data[id]?.features||[]).length,networks=[counts("hydro-live"),counts("river-live"),counts("fish"),counts("hydrobio"),counts("groundwater")];
  const aquifers=[1,2,3,4].map(h=>(state.data["groundwater-bodies"]?.features||[]).filter(f=>Number(f.properties.horizon)===h).length);
  const piezos=(state.data.piezometers?.features||[]).slice().sort((a,b)=>(Number(b.properties.profondeur_investigation)||0)-(Number(a.properties.profondeur_investigation)||0));
  const governance=[counts("syndicats-eau"),counts("syndicats-assain"),counts("syndicats-riviere")];
  const decades=[1970,1980,1990,2000,2010,2020,2026],cumulative=(id,field)=>decades.map(year=>(state.data[id]?.features||[]).filter(f=>{const y=Number(String(f.properties[field]||"").slice(0,4));return y&&y<=year}).length),riverHistory=cumulative("river-live","date_creation"),hydrobioHistory=cumulative("hydrobio","date_premier_prelevement");
  return {quality,qualityKm,prices,bins,weightedPrice,networks,aquifers,piezos,governance,decades,riverHistory,hydrobioHistory};
}
function makeCharts(){state.charts.forEach(c=>c.destroy());const d=chartData(),font={family:"Marianne"},tooltip={titleFont:font,bodyFont:font},common={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip},scales:{x:{grid:{display:false},ticks:{font}},y:{beginAtZero:true,grid:{color:"#edf1f3"},ticks:{font}}}};
  document.getElementById("dashboardKpis").innerHTML=[[`${d.quality.reduce((a,b)=>a+b,0)}`,"tronçons évalués","État écologique DCE"],[`${Math.round((d.quality[0]||0)/(d.quality.reduce((a,b)=>a+b,0)||1)*100)} %`,"en bon état","Part des tronçons classés"],[`${d.weightedPrice.toFixed(2).replace(".",",")} €`,"prix moyen pondéré / m³","Pondéré par la population"],[`${d.networks.reduce((a,b)=>a+b,0)}`,"points dans les réseaux","Comptages non dédoublonnés"],["7","masses d’eau souterraines","Réparties sur 4 horizons"],["3","zones d’alerte sécheresse","Zonage de référence"]].map(([v,l,s])=>`<article><strong>${v}</strong><span>${l}</span><small>${s}</small></article>`).join("");
  state.charts.push(new Chart(document.getElementById("qualityChart"),{type:"bar",data:{labels:Object.values(qualityLabels),datasets:[{label:"Tronçons",data:d.quality,backgroundColor:Object.values(qualityColors),borderRadius:4,yAxisID:"y"},{label:"Longueur (km)",data:d.qualityKm,backgroundColor:Object.values(qualityColors).map(c=>c+"77"),borderWidth:1,borderColor:Object.values(qualityColors),borderRadius:4,yAxisID:"y1"}]},options:{...common,plugins:{legend:{display:true,position:"bottom",labels:{boxWidth:12,font}},tooltip},scales:{x:{grid:{display:false},ticks:{font}},y:{beginAtZero:true,position:"left",title:{display:true,text:"Tronçons",font},grid:{color:"#edf1f3"},ticks:{font}},y1:{beginAtZero:true,position:"right",title:{display:true,text:"Kilomètres",font},grid:{display:false},ticks:{font}}}}}));
  state.charts.push(new Chart(document.getElementById("priceChart"),{type:"bar",data:{labels:["< 2,50 €","2,50–3 €","3–4 €","≥ 4 €"],datasets:[{data:d.bins,backgroundColor:["#d9d4f5","#9b8cdc","#6554c0","#3f2c80"],borderRadius:5}]},options:common}));
  state.charts.push(new Chart(document.getElementById("networkChart"),{type:"bar",data:{labels:["Hydrométrie","Qualité rivières","Poissons","Hydrobiologie","Qualité nappes"],datasets:[{data:d.networks,backgroundColor:["#0878d1","#009f91","#18753c","#d13b75","#8155a5"],borderRadius:5}]},options:{...common,indexAxis:"y"}}));
  state.charts.push(new Chart(document.getElementById("aquiferChart"),{type:"doughnut",data:{labels:["H1 · proche surface","H2","H3","H4 · profond"],datasets:[{data:d.aquifers,backgroundColor:["#22a7bd","#6673c8","#8a52b1","#bb477e"],borderColor:"#fff",borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{boxWidth:10,font}},tooltip}}}));
  state.charts.push(new Chart(document.getElementById("piezoChart"),{type:"bar",data:{labels:d.piezos.map(f=>f.properties.nom_commune),datasets:[{label:"Profondeur du forage (m)",data:d.piezos.map(f=>Number(f.properties.profondeur_investigation)||0),backgroundColor:"#00a7b5",borderRadius:5,yAxisID:"y"},{label:"Mesures disponibles",type:"line",data:d.piezos.map(f=>Number(f.properties.nb_mesures_piezo)||0),borderColor:"#000091",backgroundColor:"#000091",tension:.25,yAxisID:"y1"}]},options:{...common,plugins:{legend:{display:true,position:"bottom",labels:{boxWidth:12,font}},tooltip},scales:{x:{grid:{display:false},ticks:{font}},y:{beginAtZero:true,title:{display:true,text:"Profondeur (m)",font},ticks:{font}},y1:{beginAtZero:true,position:"right",grid:{display:false},title:{display:true,text:"Nombre de mesures",font},ticks:{font}}}}}));
  state.charts.push(new Chart(document.getElementById("governanceChart"),{type:"bar",data:{labels:["Eau potable","Assainissement","Rivières"],datasets:[{data:d.governance,backgroundColor:["#0878d1","#8155a5","#009f91"],borderRadius:5}]},options:common}));
  state.charts.push(new Chart(document.getElementById("historyChart"),{type:"line",data:{labels:d.decades,datasets:[{label:"Qualité des rivières",data:d.riverHistory,borderColor:"#009081",backgroundColor:"#00908122",fill:true,tension:.25},{label:"Hydrobiologie",data:d.hydrobioHistory,borderColor:"#c43c7a",backgroundColor:"#c43c7a22",fill:true,tension:.25}]},options:{...common,plugins:{legend:{display:true,position:"bottom",labels:{boxWidth:12,font}},tooltip}}}));
  const good=d.quality[0]||0,total=d.quality.reduce((a,b)=>a+b,0),pct=Math.round(good/(total||1)*100),goodKm=d.qualityKm[0]||0,totalKm=d.qualityKm.reduce((a,b)=>a+b,0);document.getElementById("insightValue").textContent=`${pct} %`;document.getElementById("insightText").textContent=`des tronçons évalués sont en bon état, soit ${goodKm.toLocaleString("fr-FR")} km sur ${totalKm.toLocaleString("fr-FR")} km recensés. ${d.quality[1]||0} tronçons sont en état moyen.`
}
async function init(){renderLayers();renderSources();const layerList=document.getElementById("layerList");layerList.scrollTop=0;await loadCommunes();await Promise.allSettled(sources.filter(s=>s.file).map(loadSource));await Promise.allSettled(sources.filter(s=>s.active).map(s=>setLayer(s,true)));layerList.scrollTop=0;requestAnimationFrame(()=>{layerList.scrollTop=0});document.getElementById("mapStatus").textContent="19 couches cartographiques prêtes · 3 sources documentaires référencées"}
document.getElementById("searchButton").onclick=search;document.getElementById("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter")search()});document.getElementById("resetView").onclick=()=>state.territory?map.fitBounds(state.territory.getBounds(),{padding:[10,10]}):map.fitBounds(BOUNDS_95,{padding:[8,8]});document.getElementById("resetPanel").onclick=()=>document.getElementById("resetView").click();document.getElementById("closeDetail").onclick=()=>document.getElementById("detailPanel").classList.remove("open");document.getElementById("clearLayers").onclick=()=>sources.forEach(s=>{const e=document.getElementById(`layer-${s.id}`);if(e.checked){e.checked=false;setLayer(s,false)}});document.getElementById("openSources").onclick=()=>document.getElementById("sourcesDialog").showModal();document.getElementById("openDashboard").onclick=async()=>{const button=document.getElementById("openDashboard"),label=button.textContent;button.disabled=true;button.textContent="Préparation…";await Promise.allSettled(["hydro-live","river-live","fish","hydrobio","groundwater","piezometers"].map(id=>loadSource(sources.find(s=>s.id===id))));makeCharts();document.getElementById("dashboardDialog").showModal();button.disabled=false;button.textContent=label};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());document.querySelectorAll(".map-kpis button").forEach(b=>b.onclick=()=>{const s=sources.find(x=>x.id===b.dataset.focus);const e=document.getElementById(`layer-${s.id}`);if(!e.checked){e.checked=true;setLayer(s,true)}});document.querySelectorAll("[data-basemap]").forEach(b=>b.onclick=()=>{const id=b.dataset.basemap;if(id===state.basemap)return;map.removeLayer(baseLayers[state.basemap]);baseLayers[id].addTo(map);baseLayers[id].bringToBack();state.basemap=id;document.querySelectorAll("[data-basemap]").forEach(x=>x.classList.toggle("active",x===b))});
const mobileLayers=document.getElementById("mobileLayers"),layerSidebar=document.getElementById("layerSidebar");mobileLayers.onclick=()=>{const open=layerSidebar.classList.toggle("open");mobileLayers.setAttribute("aria-expanded",String(open));mobileLayers.textContent=open?"Fermer":"Données"};
init();
